### ISSUE TITLE
Feature Request: Wrangle Only Specific Types of Tabs

### ISSUE THREAD

**Issue by sinatra1830** [tabwrangler/tabwrangler#112]
I like leaving tabs open as a sort of long-term to do list. I just hate having a billion facebook tabs to distract me. If you could, please add the functionality only to wrangle tabs with specific URLs. (eg. www.facebook.com).

Thanks!

**Comment by rynowin** [comment]
Duplicates https://github.com/jacobSingh/tabwrangler/issues/87

**Comment by ssorallen** [comment]
Closing as duplicate of #87.
