### ISSUE TITLE
Auto update options page

### ISSUE THREAD

**Issue by edjroot** [tabwrangler/tabwrangler#113]
I like to leave Tab Wrangler's options page open most of the time. Currently, I have to refresh the page to see newly closed tabs. It would be nice if it automatically updated the list whenever something changed.

Thanks for your attention!

**Comment by ssorallen** [comment]
I agree, this should be updating without having to refresh. This is on my list to improve.

**Comment by ssorallen** [comment]
I'd like to use [Redux](http://redux.js.org/) for the background page in order to handle this updating and connect the popup to the Store there. I assigned this to v6.0.0, the next major release, because it will include large internal changes.
