### ISSUE TITLE
Feature: avoid duplicate "wrangled tabs"

### ISSUE THREAD

**Issue by rynowin** [tabwrangler/tabwrangler#114]
Related to https://github.com/jacobSingh/tabwrangler/issues/75 but different, and avoids the form-killing problem:

I often end up with duplicate tabs in my wrangled list. (e.g. gmail.com is in there 5 times). As far as I can tell, since you've already closed the tab, form content is already gone, and IF the URLs match exactly, there's almost no value in having two of the same page in the wrangled list at the same time.

Suggestion:
- When wrangling a tab, check to see if there's an already-wrangled tab in the list with the identical URL. If there is, remove the _older_ one, to avoid duplicates.

**Comment by eorroe** [comment]
This should be configurable, sometimes doing a check by exact URL is very annoying. I'd love if this were configurable by both:

1. Exact URL Match

or 

2. Domain match and title match

I prefer the 2nd way instead of exact URL match. An option to choose between the two would be better IMO

**Comment by androiderik** [comment]
@eorroe  i agree, i'm looking for some + plus option that does this, i just want to close not exact same url, even a url that match the same domain because my url route has parameters wich i dont care 2 times, just once is enoguh.....But i send a message directly to the developers to culture free chrome plugin, or a repo in github but no answers, no solution to this ;( 
help pls

**Comment by eorroe** [comment]
@androiderik The developer behind TabWrangler is still actively developing it, I'm sure he'll respond as soon as possible.

**Comment by ingorichter** [comment]
I started to work on it. Once the PR is ready I'll let you know

**Comment by ingorichter** [comment]
@ssorallen I have an implementation for this feature.
I'm looking for feedback on the wording and if the description/explanation makes it clear enough what the different options are and what it means for the user

@rynowin @eorroe @androiderik I happy to hear your feedback for this feature. I'm currently preparing a PR for you to try it out yourself
 
![screenshot 2017-09-25 22 40 39](https://user-images.githubusercontent.com/86214/30844218-c8b561d4-a242-11e7-8a95-522271097506.png)

**Comment by rynowin** [comment]
I'm excited about this feature!

Feedback on the wording (and some on the functionality too, possibly):
1. Maybe for the radio buttons we could have a heading like: "Prevent duplicate tabs" with options of "never", "if URL matches exactly", "if hostname and title match"
2. It seems like the functionality described for exact match and hostname/title match differ in a way other than matching => the exact match option has it so that the older entry is removed, while the hostname/title option sounds like the older entry is retained and the new one is discarded. Personally, I think there's no reason to have these options differ on this behavior in addition to the matching logic. I also think that removing the older entry is a better experience, as people are more likely to care that they can see tabs that were very recently wrangled and not want a tab to be missing from that very recent list because a duplicate is buried further down the list somewhere.
3. I've got some suggestions for re-wording the explanations (below), but if you want to keep approximately the same as what you have, let me know, and I can provide more specific feedback on what you have (there are some typos, might be good to use "corral" for consistency, and I'd recommend using a clearer example, like the one below).
4. Suggested: "Never: never prevent duplicate tabs even if the exact page is already in the corral (original and default behavior). Example: A tab for https://en.wikipedia.org/wiki/Google_Chrome#Extensions would be placed at the top of the corral and an older entry will remain as well.
5. Suggested: "if URL matches exactly: if a tab with the exact URL already exists in the corral, when you wrangle this new tab it will be added to the top of the list and the older entry will be removed. Example: A tab for https://en.wikipedia.org/wiki/Google_Chrome#Extensions would be placed at the top of the corral and the older entry would be removed. If an older entry existed for https://en.wikipedia.org/wiki/Google_Chrome#Privacy it would not be removed.
6. Suggested: "if hostname and title match: if a tab with the same hostname (e.g. "en.wikipedia.org") and title (e.g. "Google Chrome - Wikipedia") exists in the corral, when you wrangle this new tab it will be added to the top of the list and the older entry will be removed, even if the URL is not an exact match. Example: If the new tab is https://en.wikipedia.org/wiki/Google_Chrome#Extensions, an older entry for https://en.wikipedia.org/wiki/Google_Chrome#Privacy would be removed.

I hope it helps! Let me know if you have any questions! Of course I am happy to discuss anything further, but of course I defer to you for final decision because you're doing all the work!

**Comment by ssorallen** [comment]
@rynowin Thanks for the thorough comment. I agree the feature's description needs some clarification to make sure users know what it's doing. I like your updates. @ingorichter, what do you think of them? I already made some changes in master but am interested to get more input.

2. I also think the feature should behave as you described it. New matching tabs should replace old matching tabs rather than renew matching tabs already in the corral

**Comment by ingorichter** [comment]
@rynowin Thanks for your feedback and suggestions how to improve that feature. I'm happy to make these adjustments and improve the wording to avoid confusion.
Regarding point 2: my working is probably misleading. For both options (exact match and URL/title match) an existing extra is retained and pushed to the top of the list. If it's not working that way, then I'm going to fix it. :-)

**Comment by ingorichter** [comment]
I've changed the wording on the description part.
What I like better is that the version in master where the header is **Corral Options**. Perhaps we should rename it to **Tab Corral Options**. Or we rename what's in my branch to **Prevent duplicate Tabs in Corral**

**That's what currently in master**

![image](https://user-images.githubusercontent.com/86214/31043088-c4830794-a56a-11e7-8c93-464091a4f8dc.png)

**This is currently in my branch with the wording update** (it's missing the last example)

![image](https://user-images.githubusercontent.com/86214/31043085-9c0a6a00-a56a-11e7-8eda-50a6899e636d.png)

**Comment by ingorichter** [comment]
BTW: this is the branch https://github.com/ingorichter/tabwrangler/tree/ingo/update-wording

**Comment by ssorallen** [comment]
@ingorichter I like @rynowin's version of the functionality too: if a tab is a duplicate it should _replace_ the duplicate in the corral. The corral will always have the newest/latest duplicate tab.

The tests show that the current functionality doesn't add duplicate tabs to the corral, which means the oldest duplicate will remain. I think the description of this should be, "replaces duplicate tab in the corral id hostname and title match":

https://github.com/tabwrangler/tabwrangler/blob/master/app/js/__tests__/tabmanager.test.js#L124

What do you think?

**Comment by ingorichter** [comment]
@ssorallen we can change to make the description clearer. BTW: It looks like https://github.com/tabwrangler/tabwrangler/blob/master/app/js/__tests__/tabmanager.test.js#L126 still uses the uppercase `HOST_AND_TITLE_MATCH` instead of the new Camelcase `hostnameAndTitleMatch`. If have this PR https://github.com/tabwrangler/tabwrangler/pull/160 to address the issue.

BTW: Thanks for updating all dependencies 👍

**Comment by ssorallen** [comment]
I did some more wording changes and moved the setting into the "Settings" section. I'd like to keep the description succinct so the popup is quick to understand. We can move longer descriptions into the README, which can serve as more like a user manual.

What do y'all think:

<img width="599" alt="screen shot 2017-10-04 at 11 33 38 am" src="https://user-images.githubusercontent.com/29612/31158944-f71bff6c-a88a-11e7-92c0-9bdb85b04cc3.png">

**Comment by rynowin** [comment]
Looks good. +1 for being succinct.

**Comment by ssorallen** [comment]
This is being pushed out in [v5.4.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v5.4.0) right now through the Chrome Web Store. Try it out, and let me know if there are any issues or places for improvement.

Thanks @ingorichter for writing the feature, and thanks @rynowin for the feedback to make it even better.
