### ISSUE TITLE
Auto open tabs

### ISSUE THREAD

**Issue by eorroe** [tabwrangler/tabwrangler#122]
What if tabs were opened automatically after the amount of tabs set for **Don't auto-close if I only have** is reached

**Comment by ssorallen** [comment]
That's cool. It'd be "Keep me at X tabs" rather than "Don't auto-close tabs if". Your browser would always have the X most recently used tabs.

It might feel strange though to try to close a tab only to have it automatically re-opened. How do you think you could re-open that without it being a surprise?

**Comment by eorroe** [comment]
I'm talking about tabs that were closed so you can finish the other thing you were working on. So a queue

**Comment by eorroe** [comment]
Basically what I'd love for TabWrangler to work like [this extension](https://chrome.google.com/webstore/detail/tabs-limiter-with-queue/kaamkonbephafcojgajnbgbdgbgbboap?utm_source=chrome-app-launcher-info-dialog) (Sadly not working for me)

**Comment by joeytwiddle** [comment]
+1 for this feature, but I would suggest:

- the minimum number of tabs can be different from the maximum
- an option to choose which queued tab to re-open: the oldest, the newest, or random

**Comment by KTamas** [comment]
I like this, though it's probably low-priority right now. PRs welcome.

**Comment by ssorallen** [comment]
Closing this as "won't fix" because this goes beyond the scope of what I would like for Tab Wrangler. Tab Wrangle closes tabs automatically but does not re-open them automatically. It's a garbage collector.

**Comment by eorroe** [comment]
By default it should work as is, but this could be an optional advanced feature.

It would be the 1st extension with both a minimum and maximum tab feature.
