### ISSUE TITLE
Restore tab history

### ISSUE THREAD

**Issue by edjroot** [tabwrangler/tabwrangler#125]
Each tab has a unique history (accessible via the "back" and "forward" buttons); such history is lost when tabs are sent to the corral. Is it possible to keep it and restore it when the tab is reopened?

Thanks!

**Comment by ssorallen** [comment]
The history of each tab is called a Session in the Chrome API. Chrome stores up to 25 closed sessions it seems. Tab Wrangler could restore the session if it still exists and otherwise fall back to the current behavior. 

https://developer.chrome.com/extensions/sessions#method-restore

**Comment by joeytwiddle** [comment]
For what it's worth, I know the FreshStart (session manager) extension can do this. I don't know how it works.

**Comment by edjroot** [comment]
Hey, thanks a lot for all the work!

I've just tested this on Firefox and it's not working. Should I open a new issue?

**Comment by ssorallen** [comment]
@edjroot Yes, please open a new issue. I’m not a regular Firefox user, so if you notice any other issues please let me know. I appreciate any testing help.
