### ISSUE TITLE
Tab lock timer reset on browser restart

### ISSUE THREAD

**Issue by BlueInt32** [tabwrangler/tabwrangler#130]
Since one of the recent releases (maybe it's due to new Chrome version), when I close Chrome the "closing in..." timing is not maintained accross Chrome restarts even though Chrome startup settings is set to "Continue where we left off". 

Observed behavior : 
- time to restart is set to 60min
- Chrome settings for tabs is "Continue where we left off"
- a tab has a "closing in" of say 18min
- chrome is closed
- when chrome is reoppened, the tab has "closing in" **reset to 60min**

Expected behavior: 
- time to restart is set to 60min
- Chrome settings for tabs is "Continue where we left off"
- a tab has a "closing in" of say 18min
- chrome is closed
- when chrome is reoppened, the tab still has "closing in" **set to 18min**

**Comment by igorsol** [comment]
From what I see in the master branch current implementation has no functionality for saving the array of the last accessed times and restoring it when the browser starts. Instead the `startup` function has this code:

```TypeScript
  chrome.tabs.query({
    windowType: 'normal',
  }, tabmanager.initTabs);
```

which just populates `TabManager.tabTimes` with `Date.now()` for each existing tab.

Thus to fix this issue two things should be done:
1. Implement save/load for `TabManager.tabTimes`
2. Modify `startup` to not overwrite last accessed times which are loaded from persistent storage. 

Original reporter mentioned that in some older version last acces times was not reset on the chrome restart. If this is true It would be great to know exactly when it was broken.

**Comment by ssorallen** [comment]
I don’t believe Tab Wrangler ever preserved tab countdowns, so I don’t think there is any previous code to look at. It would be great to persist them though. This would be a nice addition to the extension.

**Comment by ssorallen** [comment]
I'm reverting the changes made to implement this because the behavior is currently inconsistent. The code expects synchronous access to local storage, but it's async. The code that interacts with local storage needs more thought to ensure consistent reading and writing. I don't want to release a feature that half works.

**Comment by ssorallen** [comment]
This is expected behavior by at least one new user and was reported as a bug in a Chrome Web Store comment:

> It keeps resetting itself when I close the browser. It won't remember which tabs I've already locked, forcing me to reopen and re-lock them again when I realize what I'm missing.

**Comment by al4u** [comment]
hi! Any chances to get this issue solved? My tabs are kept for 1 week so, for example, a restart of the computer reverts all the tabs to the default counter which is yet 7 more days :(

**Comment by al4u** [comment]
> I'm reverting the changes made to implement this because the behavior is currently inconsistent. The code expects synchronous access to local storage, but it's async. The code that interacts with local storage needs more thought to ensure consistent reading and writing. I don't want to release a feature that half works.

hi! That's how I must had created my question yesterday (see above). Any chances not to reset timers upon restarting the browser? I'm afraid that could be a decision making point for me.

**Comment by Vondor** [comment]
Just want to push it. But in my case it is Firefox:
https://github.com/tabwrangler/tabwrangler/issues/339

**Comment by ssorallen** [comment]
This was (finally) added in [v7.2.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v7.2.0).
