### ISSUE TITLE
Option to keep persist search result

### ISSUE THREAD

**Issue by eorroe** [tabwrangler/tabwrangler#135]
This is a small feature, but that will save me a bit of time, and keep me from being distracted.

Sometimes I'm just on YouTube and want to focus on being on youtube, so I search on TabWrangler "youtube" so I can see only YouTube links. But when I open TabWrangler again, I see some other stuff and get distracted real quick wanting to open some other stuff. I know this is my fault, but an option setting to persist my last search would be nice. Plus saves me time from typing "youtube" over and over.

**Comment by KTamas** [comment]
yeah, this seems useful.

**Comment by ssorallen** [comment]
Closing this as "will not fix." Tab Wrangler's emphasis will be on finer control over when tabs get closed. If tabs get closed they should really be ones you no longer need. If you need to search frequently in closed tabs then Tab Wrangler hasn't provided the necessary tools for you to control which tabs get closed.

**Comment by eorroe** [comment]
Just thought about a good reply to your response:


> "If you need to search frequently in closed tabs then Tab Wrangler hasn't provided the necessary tools for you"

What about the people who want to use Tab Wrangler to speed up their computer by saving RAM, there are extensions that suspend tabs, but to me Tab Wrangler as a suspender is good because it closes the tabs out of sight making one only focus on what is open at the moment until one needs to reopen the closed tabs.

I have not looked at the code for this extension so I could be wrong in saying it is a small feature to implement, but if it is please reconsider for those who use Tab Wrangler with the intention of saving RAM.
