### ISSUE TITLE
Data Structure

### ISSUE THREAD

**Issue by eorroe** [tabwrangler/tabwrangler#136]
Hey I'm looking at how the data is stored in TabWrangler and it looks like you're saving the complete tab data from what the `chrome.tabs` API gives you. 

My question is why not just save the data that is necessary?

Looking at the data, it seems you only need the following:
- title
- url
- pinned

I can't seem to understand why you need to store the rest of the data, like `height`, `width` windows ID etc. Isn't the rest of the data useless? Why not save users storage data, by reducing the data per tab?

**Comment by ssorallen** [comment]
I don't believe this was given a lot of though early on; it is currently the full [`Tab`](https://developer.chrome.com/extensions/tabs#type-Tab) object returned from the `chrome.tabs` API. I agree most of that data is not needed.

In order to make #125 possible, we would also need to preserve `sessionId` if it exists.

**Comment by eorroe** [comment]
> to enable re-opening tabs in their original windows, if they exist

Is this a feature request?

**Comment by ssorallen** [comment]
It was mentioned in a feature request on the Chrome Web Store's feedback tool that I disabled when I started working on Tab Wrangler. I will open a version of it here.

**Comment by ingorichter** [comment]
We should include `mutedInfo` and `incognito`

**Comment by ssorallen** [comment]
I don't believe there is any action to take here right now. Tab Wrangler is not wasting much space currently; it's only text, which compresses easily.

I am going to close this, but please reopen if the size of TW's storage is causing functionality issues.
