### ISSUE TITLE
Re-open tabs in original windows

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#138]
If a tab's window is still open when restoring the tab, optionally open that tab in its original window.

**Comment by ssorallen** [comment]
This was effectively implemented in #125 by restoring sessions rather than opening new tabs with the existing URLs. Going further than the feature added in #125 might not be worthwhile because we'd be re-implementing the browser's own session management.

**Comment by KTamas** [comment]
yeah, let's not.
