### ISSUE TITLE
Duplicating Tabs

### ISSUE THREAD

**Issue by watagan** [tabwrangler/tabwrangler#143]
Hi,
Tabs in wrangler appear to be duplicating - sometimes get 30 or more of the same saved tab appearing, knocking out the tabs I would like to have saved.
Been happening since new version with check boxes.

**Comment by ssorallen** [comment]
Thanks for reporting this. What settings are you using? Do you manually send tabs to the corral or let them automatically close?

**Comment by watagan** [comment]
Hi Ross,
        
        The tabs are automatically added to the corral - I very rarely
        add them manually, and the affected tabs certainly weren't sent
        manually.
        
        I have a few auto-lock tabs, don't auto-close if I have 6 tabs
        open, otherwise my settings are default.
        
        The multi-copies of the same tab doesn't happen frequently -
        perhaps once a week or so.
        
        Perhaps I should remove Tabwrangler, then re-install and see if
        that fixes things? The problem only started happening after the
        new version installed.
        
        I think the product is great - very useful.
        
        Cheers,
        Jim.
        
        
      
    On 16/07/2017 7:26 AM, Ross Allen
      wrote:
    
    
      Thanks for reporting this. What settings are you using? Do you
        manually send tabs to the corral or let them automatically
        close?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jacobSingh/tabwrangler","title":"jacobSingh/tabwrangler","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jacobSingh/tabwrangler"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ssorallen in #143: Thanks for reporting this. What settings are you using? Do you manually send tabs to the corral or let them automatically close?"}],"action":{"name":"View Issue","url":"https://github.com/jacobSingh/tabwrangler/issues/143#issuecomment-315564338"}}}

**Comment by watagan** [comment]
I am using standard settings, but may have found when this happens. I set the PC to sleep overnight with Chrome still running, and when I attempt to activate Chrome, it takes quite a while to respond. It is then that I (sometimes) notice the duplicates:
![image](https://user-images.githubusercontent.com/30194752/29746625-1641496c-8b24-11e7-90d3-3c1a6feca34f.png)
This pic shows the last of a large number of duplicates.
Cheers,
Jim.
