### ISSUE TITLE
Re-enable single-click deleting of tabs in corral

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#145]
Feedback in the Chrome Store is that users liked needing only 1 click to delete a tab in the corral. With the checkboxes, deleting even a single tab requires selecting it and then clicking the delete button. Explore how deleting can be done with a single click while keeping the checkbox UI.

Initial thought: bring back the favicon -> close button on hover interaction.

**Comment by ssorallen** [comment]
I'm going to close this as a "will not fix." The benefit to the multi-select I feel outweighs the extra click it takes delete a single URL.

If anyone sees this issue and would like to try out another way of addressing this, I'm open to it.

**Comment by quintrino** [comment]
I do like the idea of the checkbox stays next to each entry but the favicon still becomes a close button if you click on it. (Or alternatively maybe a command like 'control' click causes the tab to close?

**Comment by ssorallen** [comment]
Feedback from @quintrino, #192, and others have pointed out that this feature was much loved. Let's bring it back.
