### ISSUE TITLE
Tab Lock Boxes Spontaneously Become Unchecked

### ISSUE THREAD

**Issue by bnoyes** [tabwrangler/tabwrangler#152]
For a couple of months now, I have experienced checked tab lock boxes unchecking themselves and pages then closing. There is no pattern to which pages do this - some do, some don't. Any help would be appreciated, as I'm often left going to search for a page that has closed and I didn't realize it.

**Comment by ssorallen** [comment]
Thanks for reporting this. I suspect this has to do with tabs being replaced, an effect of Chrome's tab management. @sonntag fixed this in his branch a long time ago, but the commit never made it into this version.

Commit https://github.com/sonntag/tabwrangler/commit/7d2e24f58f8163399ae669619784c5cea978dd0d needs to be ported to this repo.

**Comment by ssorallen** [comment]
Incorrectly linked to this issue from a commit.
