### ISSUE TITLE
Auto pause on computer suspend

### ISSUE THREAD

**Issue by k2l8m11n2** [tabwrangler/tabwrangler#155]
I like use this extension on my Chromebook, and I frequently suspend it (close the lid) instead of turning it off. However when I open it later, all my tabs are closed. Is it possible to implement an option to automatically pause Tab Wrangler on computer suspend?

**Comment by ssorallen** [comment]
Thanks for the issue, and yes, absolutely. This feature has been wanted for a while and is tracked in #5. Closing this as a duplicate.
