### ISSUE TITLE
Tab corral sync

### ISSUE THREAD

**Issue by k2l8m11n2** [tabwrangler/tabwrangler#156]
Is it possible to implement syncing of tab corral? (Much like the settings sync which is working now)

**Comment by ssorallen** [comment]
Yes definitely, thanks. This is another feature that has been requested a few times, and it would be great to add. This is tracked in #83.

**Comment by k2l8m11n2** [comment]
Sorry for the duplicates, I should've looked more thoroughly.

**Comment by ssorallen** [comment]
@k2l8m11n2 No, not a problem at all. Please open any issues you want. I have a general idea of the open ones and can do the de-duplication pretty quickly.

**Comment by tryrebooting** [comment]
Hi, I wanted to piggy-back on OP's request for sync, specifically the closed (wrangled) tab history to sync across browser sessions.
