### ISSUE TITLE
lost tabs from tab wrangler (win 10 crash)

### ISSUE THREAD

**Issue by jointyjointy** [tabwrangler/tabwrangler#159]
Hi everyone, 
Few days ago my system crashed and i could not repair it , couldnt even go into safe mode , so i had to remove all. I had about 100 tabs stored in tab wrangler and everytime chrome crashed they were there , before i formatted disk i copied chrome folders  but now i dont know how and where i could get these tabs ? i chcecked tab wrangler -extension folder but did not succeeded , if anyone could help me i would be thankfull

**Comment by ingorichter** [comment]
The tabs are stored in local storage of your browser. This is an internal database that webapps/extensions can store data. Which Chrome folders did you copy? If you copied the data folder of Chrome, then you might be able to recover the tabs from local storage.

**Comment by jointyjointy** [comment]
i copied both i have this Local storage folder, but the files inside are just some urls that i visited, not the tabs that i need c, or am i doing something wrong ?

**Comment by ssorallen** [comment]
Please check #126, which is where another person was looking to recover data stored by Tab Wrangler. You might also check this Super User question about where Chrome stores localStorage from extensions: https://superuser.com/questions/507536/where-does-google-chrome-save-localstorage-from-extensions

Tabs are stored only in localStorage, but settings are synced via Chrome if you are signed into Chrome.

You can always find old tabs in chrome://history as well.

**Comment by ssorallen** [comment]
If none of those work for you, please let me know.
