### ISSUE TITLE
One Tabs does not close it

### ISSUE THREAD

**Issue by cichi76** [tabwrangler/tabwrangler#161]
I have a problem with this extension, if I loaded only one tab does not close it, but if I have more than one it closes it.

**Comment by cichi76** [comment]
After 4/5 seconds restart the countdown.

**Comment by ssorallen** [comment]
Do you have minimum tabs set to 0?

**Comment by cichi76** [comment]
Of course, but the result is the same. if I have only one tab open after 4/5 seconds the countdown starts again

**Comment by ssorallen** [comment]
The fix for this went into [v5.6.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v5.6.0).
