### ISSUE TITLE
Anyway to retrieve lost tabs?

### ISSUE THREAD

**Issue by ghost** [tabwrangler/tabwrangler#164]
I saw that the "Remember up to XXX closed tabs" option can be set higher than 500. However, when you click out of the extension it only takes the first number. So for example, if I selected 999 tabs, then it defaults back to 9. 

I quickly realized that since my tabs were set to 9, the remaining tabs were dumped. Is there any way to retrieve them from some log on my computer?

**Comment by brandondees** [comment]
this issue makes the extension unusable for me, unless there is an option to disable this limit altogether.

**Comment by ssorallen** [comment]
Chrome Extension local storage is written to disk. Check out #159 for more details.

If you dropped the limit to something smaller than the length of the list, the tabs might be gone. Apologies for that, that is not a good experience at all.

#166 will remove the upper limit, but that might not have prevented the issue you ran into. The setting should confirm that you want to make the change and warn you that the list will be truncated if you reduce the limit. I opened #167 to warn about this.

**Comment by menacel** [comment]
Thanks ssorallen!

I found the extension folder, but when I open the ldb file it asks for me to enter the key used to encrypt the database. Is there a default key/password that is used to open the ldb file?

**Comment by ssorallen** [comment]
@menacel I am unfamiliar with the LDB file that extensions create. Sorry I can't offer more help. If you do find an answer, it would be great if you could post it here.

**Comment by ssorallen** [comment]
Closing this out as v6 has been out for a while and no longer causes data loss.

**Comment by KTamas** [comment]
i would love this, but it's not a priority right now i think. PRs welcome.

**Comment by ssorallen** [comment]
This was from an issue with an old version of Tab Wrangler. This is no longer an issue.
