### ISSUE TITLE
number limits for timer and open tab limit seem to have arbitrarily low maximums, no UI hint or validations

### ISSUE THREAD

**Issue by brandondees** [tabwrangler/tabwrangler#165]
I don't see other issues related to this, but I installed the extension to experiment with it as an alternative to manually controlling OneTab and TGS. It's common for me to open hundreds of tabs at a time when doing research, and it's important to not lose track of them. This extension looks like it only supports up to 30 open tabs, and I'm not sure about the time limit but it seems to have an arbitrary limit also. If there are good reasons for these input limits, I believe the inputs should have validations and UI hints explaining what to expect, rather than unexpectedly resetting to a low number after I input a high one. If I had been careless, I could have lost some important information by mistake.

If these limits are arbitrary, I would like for them to be raised to whatever the reasonable maximum supportable values actually are.

**Comment by ssorallen** [comment]
Those limits are arbitrary and were set a long time ago. There is no technical reason to have an upper limit on either of those settings. I'm fine removing them.

Thanks for taking the time to write the feedback. I'll open an issue to remove the limits.

**Comment by brandondees** [comment]
to be clear, if there's any high number that will overflow or become unstable or whatever, i'd be fine with those limits for the sake of protecting data, but the UI should either reflect the limits or not impose them.

**Comment by ssorallen** [comment]
@brandondees Let's remove the limits. I'm going to close this question and track the new feature in #166. Please reopen or comment in #166 if you have any other feedback.

**Comment by brandondees** [comment]
thanks @ssorallen really appreciate it

**Comment by ssorallen** [comment]
This change was included in [v5.5.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v5.5.0), which has been uploaded to the Chrome Webstore. Tab Wrangler should update automatically for you soon.

**Comment by brandondees** [comment]
thanks again @ssorallen definitely much improved UX, i'll start experimenting with this for my workflow now
