### ISSUE TITLE
Remove upper limits for minTabs and minutesInactive

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#166]
* `minTabs` has an upper limit of 30
* `minutesInactive` has an upper limit of 7200 minutes

Both limits are arbitrary and not based on technical limitations. As mentioned in #165, these limits might prevent some users from using the extension. Let's get rid of them.

**Comment by Boscop** [comment]
@ssorallen Hey :)
Thanks for making TabWrangler. It's quite useful, but the version in chrome webstore still has the 7200 min limit :/
In my use case, I only want to close tabs that I haven't visited in months!
Unfortunately there is no other extension like this. Could you please push the new version to the chrome webstore that doesn't have this limit? (Such that it also supports very high numbers, e.g. 3 months are 131400 seconds.)

Btw, does TabWranger only start counting the age of tabs that were opened after the extension was installed?
E.g. if the user sets the limit to 3 months and has many tabs that are over 3 months old at the point in time when the extension gets installed, does TabWrangler immediately close those old tabs (it should ideally) or will it take another 3 months until it closes them?
