### ISSUE TITLE
Where and when are tabs saved (without exporting)?

### ISSUE THREAD

**Issue by dragGH102** [tabwrangler/tabwrangler#169]
Hi,

great extension! It seems a great replacement for The Great Suspender + Tabli altogether.

I was just wondering: are tabs saved in bookmarks (and synced across devices)? 
Also, does the extension also keep track of tabs which it didn't close?

Thanks in advance

**Comment by quintrino** [comment]
I know that there is discussion about syncing across browsers at https://github.com/tabwrangler/tabwrangler/issues/83 but it's not currently implemented. 

I'm not sure I follow the question about tracking tabs it didn't close, do you mean something similar to Chrome history?

**Comment by dragGH102** [comment]
@quintrino my understanding is that this extension saves the tabs it actually closes.

What about the tabs which are there but were Not closed by this extension?

**Comment by ssorallen** [comment]
@dragGH102 You can always access your history (all tabs you've opened) in Chrome's own History. Paste chrome://history into your address bar or go to History > Home in the menu. That will contain all tabs, including tabs closed by Tab Wrangler.

Tab Wrangler only keeps a list of the tabs it closes.

**Comment by dragGH102** [comment]
makes sense. thank you

**Comment by ssorallen** [comment]
> just one more question: any way to access tabs closed by Tab Wrangler from other devices?

That is a long-standing request that is tracked in #83. I have not yet been able to work on it but would appreciate any contributions toward it. I agree it would be an excellent feature to have.

**Comment by dragGH102** [comment]
Thanks for letting me know. as I didn't have hands on with building extensions, I'll close this. and I'll looking for that issue to be closed whenever that happens :)
