### ISSUE TITLE
feature request: add expiring tabs to pinboard instead of losing them

### ISSUE THREAD

**Issue by brandondees** [tabwrangler/tabwrangler#170]
for me, open tabs are a kind of spatial bookmark and i aggregate lots of them for future reference. after ignoring a given open tab for a while, it becomes safe to assume that i am not actively engaged with that type of information for my current activities and it can be closed/hidden somewhere, but i usually still do want the url archived somewhere searchable for future reference. i've played with OneTab, manually adding browser bookmarks, and manually adding cloud bookmarks using various services (pocket, delicious, pinboard, etc) and it's just too tedious given how many "look at this later" tabs i open in a typical day. if the bookmark archiving part could be automated by the tab manager extension that'd be the whole package for me, both efficient browser workspace and safely archived links (not bound to a particular device storage), and automate away all the tedious management of reloading a url, clicking various things to store it for later, then closing it.

**Comment by brandondees** [comment]
If I find some time, I may be willing to work on the code for this myself, if it seems like an acceptable contribution.

**Comment by keyoti** [comment]
Sorry, maybe I'm not reading closely enough, but isn't what you described what this extension does already?

**Comment by brandondees** [comment]
well i don't see any options to send urls to an external service, and everything i'm seeing implies there is a max number for closed tab url storage, beyond which they are simply deleted, presumably.

**Comment by johnw42** [comment]
Based on looking at the manifest file, I think closed tabs are stored using Chrome's [chrome.storage.local API](https://developer.chrome.com/extensions/storage), which has a quota of about 5 MB, so you should be able to increase the limit up to a very high number without causing any problems. If that's not enough, you can request the `unlimitedStorage` permission and store as much as you like.

**Comment by XxX-Force** [comment]
Yes, but if I understand correctly, he still wants to archive the URL's permanently somewhere. I too would like a feature similar to this, as at the end of a session I will always "Bookmark all tabs" and store them in a folder labeled by date. Thank you.

**Comment by ssorallen** [comment]
Closing as "will not fix." If you are reaching the 1,000 tab limit of Tab Wrangler and still wanting to search then the browser's history will be what you want.
