### ISSUE TITLE
Larger font / zoom option?

### ISSUE THREAD

**Issue by goldtreefrog** [tabwrangler/tabwrangler#173]
The text in the Tab Corral and the Tab Lock is smaller than anywhere else. I can barely read it. It is even smaller than the text on my Chrome tabs when they are open.

I would like to be able to adjust the font size.

**Comment by ssorallen** [comment]
As a workaround for now, you can right click the Tab Wrangler icon and select "Options". That will open the popup in its own tab, and inside that the tab Chrome's normal zoom will adjust the size of Tab Wrangler's text.

**Comment by ssorallen** [comment]
With v6.6.0+, the font-size adjusts with the font-size of your browser. Adjust the font-size in your browser's settings, and you should be set. Let me know if you have any other issues with this.
