### ISSUE TITLE
spanish latin america

### ISSUE THREAD

**Issue by 3pelin** [tabwrangler/tabwrangler#175]
I want to help with the translation into Spanish, it is a very useful tool, being in another idiona would help your distribution

**Comment by ssorallen** [comment]
A Spanish translation would be fantastic. I'm happy to help extract the strings so you can translate them.

Tab Wrangler will need to use the [`chrome.i18n`](https://developer.chrome.com/extensions/i18n) API to support multiple locales.

**Comment by ssorallen** [comment]
Please check out the [CONTRIBUTING.md](https://github.com/tabwrangler/tabwrangler/blob/master/CONTRIBUTING.md) doc for how to contribute Spanish translations. If you have questions about the process, feel free to ask the questions here.

**Comment by ssorallen** [comment]
If you are still willing to help out, please check out [Tab Wrangler's Crowdin project](https://crowdin.com/project/tab-wrangler). It's a platform for contributing translations. Tab Wrangler's strings are all up there, so you just need to use their interface to contribute.

👍

**Comment by 3pelin** [comment]
Of course, thank you

2018-07-31 10:00 GMT-05:00 Ross Allen <notifications@github.com>:

**Comment by ssorallen** [comment]
Chrome only supports the locales `es` and [`es_419`](http://www.localeplanet.com/icu/es-419/index.html). `es` is Spain Spanish and `es_419` is "Latin America Spanish".

Crowdin doesn't specifically list either of those locales, so:
* `es_ES` (Spain Spanish) in Crowdin is for Tab Wrangler's `es` locale
* [`es_MX`](https://crowdin.com/project/tab-wrangler/es-MX) (Mexico Spanish) in Crowdin is for Tab Wrangler's `es_419` locale.

If you'd like to contribute Latin America Spanish, please add translations to `es_MX` in Crowdin.

Thank you!
