### ISSUE TITLE
Locked tabs are closing

### ISSUE THREAD

**Issue by bnoyes** [tabwrangler/tabwrangler#179]
Hi,

I had this issue once before and it was fixed, but now it has shown up again. Many of my locked tabs keep closing by themselves (they somehow become unlocked and I don't know how).

Thanks,
Brigg

**Comment by ssorallen** [comment]
Thanks for the issue, and sorry about that.

Are the tabs auto-locked (meaning they match one of your whitelist patterns), or did you lock them manually?

**Comment by bnoyes** [comment]
Manually

Brigg Noyes, PhD

**Comment by ssorallen** [comment]
Do you relaunch your browser often? I'm wondering if this is a duplicate of #102. Currently the "locked" status of tabs is not stored, so if you relaunch they will be unlocked.

**Comment by KTamas** [comment]
@jay3fer @keyoti @bnoyes has this happened since?

**Comment by pooyadavoodi** [comment]
This started to happen to me in the last few weeks. I had seen it months ago too and it got fixed, but now it seems to be back.

**Comment by ssorallen** [comment]
I implemented a fix for this in https://github.com/tabwrangler/tabwrangler/commit/0ded8283f9a8f490d33e188d765422c5f50374d5 but never released it. I will get this into v6.11.0 and update this issue when it is available.

**Comment by ssorallen** [comment]
This was fixed in a v7 release, and locked tabs persist across launches of the browser. If this is still an issue please re-open.
