### ISSUE TITLE
can not "save and close immediately" on google spreadsheets. 

### ISSUE THREAD

**Issue by eugenosm** [tabwrangler/tabwrangler#189]
Hello
Can you add tab wrangler submenu to drop-down menu on the tab header, not only the page?
this drop-down menu disabled on google docs (at least on spreadsheets) pages, but works on tab header.

best regards.

**Comment by ssorallen** [comment]
Thanks for bringing this up. This is unfortunately not possible with the current Google Chrome [`contextMenus` API](https://developer.chrome.com/extensions/contextMenus). Extensions are only allowed to add items to context menus that are created when clicking on the content of windows. The context menu that appears when you context-click on an actual tab is not editable currently.

You can configure Tab Wrangler's keyboard shortcut for "Close current tab and save to corral". You can use that combination when viewing Google Spreadsheets.

**Comment by ssorallen** [comment]
I am going to close this because the context menu API has been the same for years, which I believe means it is unlikely to change. I found a thread dated 2011 asking about editing tab context menus: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/N8utMDdAh3E
