### ISSUE TITLE
Does hovering mouse over tab' header counts as 'use'?

### ISSUE THREAD

**Issue by igorsol** [tabwrangler/tabwrangler#191]
It seems that hovering mouse over tab's header counts as 'use' and resets tab's timer? If so then it would be cool to have a checkbox in options to switch this off.

**Comment by ssorallen** [comment]
@igorsol Thanks for opening the issue. Did you have more than your minimum number of tabs open when you saw the timer reset?

Hovering over a tab in the tab bar should not reset its timer. Only making it the active tab in the window (by clicking it, Ctrl+Tab'ing to it, etc.) resets its timer.

**Comment by igorsol** [comment]
I just installed this extension and i set up maximum timeout value (7200 minutes). And I have ~2.5 times more open tabs than my minimum number of tabs.

**Comment by igorsol** [comment]
Ah, sorry it seems the issue is not related to mouse hover. I have 4 chrome window with open tabs and i just switch from window to window and click the tab wrangler icon to see timers in the "tab lock" list. After some playing with this I have roughly half of the timers reset. I cannot identify exact sequence to reproduce this but I am sure I did not activate those tabs.

**Comment by igorsol** [comment]
Now I restarted my browser and all my tabs timers have been reset. Is this by design?

**Comment by ssorallen** [comment]
> Now I restarted my browser and all my tabs timers have been reset. Is this by design?

That is a bug that is captured in https://github.com/tabwrangler/tabwrangler/issues/130. It was an oversight and not intentional. It'd be great to get that fixed.

**Comment by ssorallen** [comment]
> I have 4 chrome windows

Tab Wrangler counts tabs per window, not all tabs for an account. If you have 10 windows open with 1 tab each, Tab Wrangler counts only 1 tab per window not 10 tabs total.

#95 is open to make the "per window" functionality an option. Would that fix the issue you're seeing?

**Comment by igorsol** [comment]
> #95 is open to make the "per window" functionality an option. Would that fix the issue you're seeing?
Yes, from my point of view current behavior is confusing. I think tab limit option should refer to the aggregated number of tabs in all windows.

**Comment by ssorallen** [comment]
I believe all questions you had are captured in other issues. I am going to close this issue. Please re-open or comment on the other issues if you have other feedback. Thanks again for contributing.
