### ISSUE TITLE
Explore Tab Wrangler for Safari

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#194]
What does it take to create a Safari extension? Is any of this work reusable?

**Comment by kimpomares** [comment]
Yeah, a tab manager for Safari like tab wrangler would be awesome!

**Comment by KTamas** [comment]
Safari 13 threw out its extension system and now you have to make your extensions in XCode (see https://developer.apple.com/safari/extensions/). My educated guess is you would basically have to write a separate version for Safari at least.

**Comment by KTamas** [comment]
i think we're open to this but we have no resources or much motivation to work on this (i personally don't use safari unless i'm forced to). so if someone wants to work on it, go ahead.

**Comment by bonafideduck** [comment]
I created an extension for Safari called CloseTabs.  I then ported it to Chrome.  I just now discovered TabWrangler when [cantonalex](https://github.com/cantonalex) mentioned it in BonafideDuck/CloseTabsExtension#3. This has almost all the same features as my DuckTabs extension except I also have a tab autosort option.  But since Safari currently doesn't support tab.move, that is not an issue for Safari.

**Comment by ssorallen** [comment]
A port of TabWrangler to Safari would be amazing, I'd be happy to review any changes related to that.

**Comment by bonafideduck** [comment]
@ssorallen , I have found that OSX doesn't play nicely with the modules.  So I did a `yarn upgrade --latest`.  (see [this PR](https://github.com/tabwrangler/tabwrangler/pull/369)).  Before I continue down this path, would such an update be too much or a bad idea?

**Comment by bonafideduck** [comment]
@ssorallen , I expect to break this into 3 PRs.  #2 is controversial, so I'd like to get a your approval before starting.

1. Update node_modules to allow `yarn build` and `yarn start` to work on macOS Monterey.
2. Add [polyfill](https://github.com/mozilla/webextension-polyfill/) and convert all `chrome` calls to `browser`.
3. Add support for Safari builds.

**Comment by ssorallen** [comment]
@willswire Amazing, thank you for the update. Do you plan to keep the extension open source and/or free? I will try it out once you are able to get it into the App Store.

**Comment by ssorallen** [comment]
Closing as "will not fix" since I do not use Safari regularly and do not plan to develop for it. Always open to pull requests should someone find this in the future.
