### ISSUE TITLE
Russian description for Chrome extension page

### ISSUE THREAD

**Issue by Voknehzyr** [tabwrangler/tabwrangler#199]
I wrote Russian description for Chrome extension page, it will help other Russian users to find this extension and use it. Also I added more detailed text from myself. 👍 
```
**Автоматически закрывает неактивные вкладки и упрощает их возврат**
 - Автоматически закрывает неиспользуемые вкладки по истечению назначенного Вами времени
 - Сохраняет закрываемые вкладки, их легко открыть заново
 - Синхронизация Chrome сохраняет настройки между компьютерами
 - Не закрывает закрепленные вкладки
 - Предотвращает закрытие нужных вкладок

Но не переживайте, автоматически закрытые вкладки безопасно сохранены и находятся в Списке вкладок. Имеет большое количество настроек и является совершенно потрясающим решением для Вас. Оно спасёт ваш компьютер от большой нагрузки.

Слишком много вкладок? У Вас есть зависимость от вкладок? Tab Wrangler закрывает вкладки которые Вы давно не используете.

Иконки предоставлены Fat Cow / famfam fam.


Внимание: Не сохраняет введенную информацию на странице!
--------------------------------------------------------------
Это похоже на историю, когда страница будет закрыта, все, что вы делали с ней, исчезает. Я рекомендую расширение Lazarus, если для Вас это проблема. Если Вы снова откроете закрытую страницу, её изменения не будут сохранены.
```

**Comment by ssorallen** [comment]
This is excellent, thank you! Once I push a release with your Russian translation, then the Chrome Web Store will allow me to add a Russian translation for the extension's page. I will push out a release this week.

**Comment by ssorallen** [comment]
I added your Russian description to the Chrome Web Store. Thanks again for the translations ✨.

**Comment by Voknehzyr** [comment]
Wait, you need to change 'Automatically closes inactive tabs and makes it easy to get them back' to '**Автоматически закрывает неактивные вкладки и упрощает их возврат**' with removed '*' and remove this one from description. 😄

**Comment by ssorallen** [comment]
@Voknehzyr Thanks for pointing that out! The description needed to be extracted to the messages file. I copied your translation into the Russian messages file.
