### ISSUE TITLE
"Min tabs" setting only counts tabs per window instead of total tabs. 

### ISSUE THREAD

**Issue by GenericPseudonym** [tabwrangler/tabwrangler#201]
If the user has e.g. 2 windows with 10 open tabs each, and the minimum tab count set to 5,  the expected behavior is that all but 5 of those 20 total tabs will get "wrangled".
The actual behavior is that 10 tabs remain -- 5 in each window.

**Comment by ssorallen** [comment]
Thanks for bringing this up. This has been a long-standing request, and I would be happy to see it implemented because a lot of users would like it. Let's track it in the original issue, #95.
