### ISSUE TITLE
Popup time to screen regression

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#204]
Switching to Chrome's cache for favicons (e7afdb7a40d3be7b4bdd3d7c3078fb723bdc4491) was a performance regression, not an improvement. The popup takes considerable more time rendering all of the favicons.

Re-add lazy images or use something like [react-virtualized](https://github.com/bvaughn/react-virtualized) to render only small pieces of the table at a given time to get the speed back.

**Comment by ingorichter** [comment]
does this cause the delay and flicker on Windows? I haven't seen the flickering and delay on my Mac

**Comment by ssorallen** [comment]
@ingorichter I don't have a Windows machine to test, so I'm not sure. Did you recently start seeing the flicker?

I can revert the favicon change if it caused more problems than it fixed.

**Comment by ingorichter** [comment]
I haven't noticed it before, but it seems that after your change that there was a noticeable flicker. I can try with an older version to check if it was introduced by your change.
