### ISSUE TITLE
Feature request: restore scroll bar position in restored tabs

### ISSUE THREAD

**Issue by johnw42** [tabwrangler/tabwrangler#206]
On very long pages, losing your position within the page can be pretty annoying. It would be very handy if Tab Wrangler would remember the position of the scroll bar(s) when it closes a tab.

**Comment by ssorallen** [comment]
Thanks for the issue. If Tab Wrangler is able to restore sessions rather than re-open URLs, we would get this feature for free. #125 tracks restoring sessions, so I am going to close this issue and track it there. Please follow #125 if you'd like to know when this feature gets added.
