### ISSUE TITLE
Auto close Print tabs

### ISSUE THREAD

**Issue by bloomfields** [tabwrangler/tabwrangler#207]
Want to auto close after the page is sent to the printer/pdf.

**Comment by ssorallen** [comment]
Thanks for the suggestion.

If you leave your print tabs open after printing, they will be cleaned up like other regular tabs. Detecting what's happening inside of tabs is beyond the scope of Tab Wrangler. TW knows the URL and history of tabs, but it doesn't know what's happening inside of them. I'd like to keep it that way to restrict the permissions that Tab Wrangler needs to request.

There is a [`printerProvider` permission](https://developer.chrome.com/extensions/printerProvider) that might make this feature possible, but printing requests are not tied to a tab so it would not be possible to close the associated tab when a print job is requested.

I am going to close this one, but I appreciate the suggestion.
