### ISSUE TITLE
Unable to export from the popup

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#213]
The "Export" button only works from the Options page. This seems to be a recent change in Chrome.

The workaround for now is to visit Tab Wrangler's Extension Options page (right click Tab Wrangler's icon and select *Options*). Maybe there is a way to workaround this.

**Comment by ingorichter** [comment]
Hm, I don't have any issues with it. I tried it on macOS and Windows with Chrome 64.0.3282.186.
After updating Chrome on Windows to 65.0.3325.146, it stopped working.
I need to look at it tonight.

**Comment by ssorallen** [comment]
@ingorichter You can still export if you right click the Tab Wrangler icon and do it from the *Options* view. Chrome 65 made some big changes, but I haven't yet looked for a list of what changed for extensions.

**Comment by ssorallen** [comment]
As of Mac OS Version 66.0.3359.117 (Official Build) (64-bit), this issue has been resolved. Since this was a temporary issue with Chrome itself, I am going to close this without a fix and say it was Chrome's fault and not ours.
