### ISSUE TITLE
Incorrect tab disappearing when clicking trash icon

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#216]
I started deleting various tabs out of my wrangled area and noticed that on more than one occasion, about every 4 to 7 clicks, the tab i chose to delete is not the one that got deleted, this also happens for tabs i click to reopen. What seems to be happening, is i click delete or click on link to reopen, and a DIFFERENT tab gets deleted from the list. the list count goes down by one, the clicked link effectively is no longer under your mouse but one row higher. example: link "how a tv works in slow motion" is under my mouse. I left click the link, and that correct link is placed into a tab. however, the link remains in the wrangled list only one row higher. yet the list is diminished by one. I have not figured out how it decides which link is removed, but it is removing them. When i was in time descending, it removed the top 4 links. I did a search for them, and they are not present. to put it plainly, the link you are manipulating and the link the program decides to remove from the wrangled list is not always the same.

Originally mentioned in #192

**Comment by ssorallen** [comment]
This issue might be mitigated or fixed entirely when implementing #113. The state of the popup's UI might be inconsistent until a central store, like with Redux, is used to consistently update the popup.

**Comment by Papa2Cherries** [comment]
Did this issue get resolved?  I have completely stopped using the extension, paused indefinitely, and am unable to pull old tabs out of the coral due to the bug of losing them.  This bug fix is paramount.  Please, i will do what i can to help, but make this a priority.

**Comment by ssorallen** [comment]
This issue is not resolved, and I believe the solution will take a lot of detailed, but ultimately good and necessary, work.

The storage provided for extensions is asynchronous, but Tab Wrangler was largely written to treat it as synchronous. [settings.js](https://github.com/tabwrangler/tabwrangler/blob/master/app/js/settings.js), for example, added a "cache" early on to provide a synchronous interface to the asynchronous storage. This is where I believe your bug occurs: your clicks occasionally happen before a read or a write completes to the async store.

1. Click "Delete" button on tab ID 1: `cached tabs: [{id: 1}, {id: 2}]`
2. Tabs Array updates and calls `chrome.storage.local.set`: `cached tabs: [{id: 2}]`
3. Click "Delete" button on tab ID 2: `tabs: []`
4. Tabs Array updates and calls `chrome.storage.local.set`: `cached tabs: []`
5. `chrome.storage.local.set` call from step 4. completes: `stored tabs: []`
6. `chrome.storage.local.set` call from step 2. completes: `stored tabs: [{id: 2}]`

This is a common problem (imagine the calls to `chrome.storage.local` are instead network requests to some backend service) that needs a proper solution. I would like to solve it at the same time as #113, which would included adding something like [Redux](https://redux.js.org/) so Tab Wrangler has a proper flow for updates to its store and then implement a queue for handling your bug.

I don't yet have a timeline for fixing this, but I would be grateful for any contributions.

**Comment by joeytwiddle** [comment]
Sadly I can't give you more time, but I would be willing to make a financial contribution if someone can fix this issue in 2018. Let's say $50. Not quite enough to retire on. 💰 🌴

**Comment by ssorallen** [comment]
@joeytwiddle I appreciate the offer, but there's no need. I have been working a large infrastructure change that fixes the issue I described in my previous comment. I'm adding Redux backed by your browser's storage, which is far more predictable than the current implementation.

My work is all in the [`redux` branch](https://github.com/tabwrangler/tabwrangler/tree/redux). Feel free to check it out, but don't use that code to run in the same Chrome Profile where you have the production version of Tab Wrangler installed! It'll likely ruin your data at the moment. The upgrade will be seamless for all users once it's ready to ship though.

**Comment by ssorallen** [comment]
@joeytwiddle Once that Redux change is in, I plan to fix many outstanding issues. I can't promise a timeline at the moment, but within 2018 is almost certain.

**Comment by Papa2Cherries** [comment]
If this is closed, does that mean the issue is fixed or still present?  I am not too familiar how to read the subtle meanings of github, so if you can spell this one out I would appreciate it.  I can’t wait to use this extension again, but it has been on permanent hiatus since the discovery of this incorrect behavior.

**Comment by ssorallen** [comment]
@Papa2Cherries Thanks for the interest. This bug is in master but not yet in a release. Release v6.0.0 will include this bug fix and more general stability. I will comment on this issue again when v6 is pushed out.

**Comment by Papa2Cherries** [comment]
When you say the "bug is in master” do you mean the bug fix is in master? If so im willing to go the extra mile to install now the master version of this before the release version.  My tabs are so overwhelmed. If you feel v6.0 is going to be out soon so going through the hassle is not worth it, then I can wait.  You did mention that one should not mix the master with the release as data issues may ensue.  I define soon as “a few weeks” anything a full month or longer would not be considered “soon.”  This is just to help give you a reference to an ambiguous word i used for time in a question, not to force a deadline.  If i believed in god, you would be doing his work.  Much appreciation.

**Comment by ssorallen** [comment]
"Soon" is almost certainly within the next week. There's another manual test or two I want to run a few times, and then I'll push out v6.0.0.

**Comment by ssorallen** [comment]
Oh yes sorry I mistyped. "bug is in master" should be "bug **fix** is in master".

**Comment by Papa2Cherries** [comment]
Color me excited.  Also, with these improvements, what is going to be the limit of tabs or will 500 be the limit? Im worried when i restart this extension, i will go over very quickly as i had close to 400 before and im most certainly at that number without the extension.  what will happen if i turn it on and i have more than the limit.  I recall you wrote once something about too much may hinder the extension, but is that on less robust computers or would all powerhouses have that same problem?  

PS: thanks for the quick responses.

**Comment by Papa2Cherries** [comment]
thanks, clicking and reading on it now

**Comment by ssorallen** [comment]
While v6.0.0 did mitigate this problem, I don't think it is entirely fixed. I improved some of the data issues, but there is still some incorrect behavior if you click the trash icon fast enough multiple times.

For my future self:
CorralTab is getting its list of closed tabs by calling [`getState` on the store (via tabmanager.js)](https://github.com/tabwrangler/tabwrangler/blob/0d42b9bb630bc1d2fc63dee64d0409e65e95b00f/app/js/CorralTab.js#L226), but the list it is displaying is being passed to it by Redux's `connect` wrapper. Their sources of truth are different, and clicking fast enough can mean they are not the same value. CorralTab needs to act on the same list of tabs that is passed into it, not make another call to `getState`.

**Comment by Papa2Cherries** [comment]
i did just notice that 6.0 is out, and went to my wrangled addon and it is updated, yet paused with the database from 4 months ago.  unfortunately, this issue is still very present and alive in 6.0.  I was clicking on links to open them up in a new tab and sometimes they would not remove yet a new tab was opened, found out that something out of my search parameters was being removed as the total list was diminished by 1.  i confirmed this over 5 separate times.  Strangely, i tried something new that might also help find the fix for this.  I did a search, which came up with a bunch of  youtube videos, then clicked the icon to select all, then hit delete.  when that happened, the list diminished by the correct amount, BUT, more “youtube” videos were still present.  So what appeared to happen was the correct amount of links disappeared, but the ones checked were not all the right ones, or if they were, they did not get removed but some non youtube links did.  I did do this incredibly slowly, so speed of clicking was not a factor.   I have not  unpaused the extension yet from 4 months ago, so perhaps this is just an issue with the old database?  (that is just speculation to help you along, perhaps).  if there is something i can do to reset my database and work with you, i am willing to kill off all the old ones and just start with the new hundreds and see if it persists if you think that may fix the problem from the old database merging with the new.  I will leave paused until i hear back.

**Comment by ssorallen** [comment]
@Papa2Cherries Thank you for testing and for the details. The storage still needs a few changes to fully use the new storage area, and at least then tracing any remaining issues will be straightforward. The original storage was inconsistent and led to difficult-to-debug issues like this one.

I'll keep tagging commits with this issue number as I replace remaining old storage logic.

**Comment by ssorallen** [comment]
I found a highly likely culprit.

The extension has always assumed that a tab ID is unique. They are unique, but only within a given browser session. Tabs closed over long periods of time, like the ones saved in Tab Wrangler's storage, will recycle IDs because they are from many different sessions.

Currently in my production version of Tab Wrangler I have 499 closed tabs, and there are only... 428 unique IDs within that list. Closing tabs and a lot of other manipulation relies on IDs, but that obviously will not work. This explains why seemingly random tabs are removed from the list; it's removing the first tab in the Array with the ID of the one you want to close, which isn't necessarily the one you selected.

A potential solution is to always pass references to the `chrome$Tab` object rather than pass around tab IDs. The `chrome$Tab` Object will of course be unique, and since the reference is passed around rather than a proxy (like an ID) then there's no potential for selecting the wrong one.

**Comment by Papa2Cherries** [comment]
I like it, thanks for keeping a keen eye on this issue.  Numerically, your discovery makes complete sense of the issue.  In testing you probably have a bunch of tabs closed in one session.  I have had many many sessions thus it makes sense why some get through and others take one click to clear and still others take several clicks.  (clicks being delete or link click to open in tab).  Is this potential solution something easy to implement, and/or will it require a completely reset from scratch database?

**Comment by ssorallen** [comment]
@Papa2Cherries Nope, no changes required to Tab Wrangler's storage. Commit dbee3fd addresses the primary issue.

I confirmed my suspicion by creating 500 tabs with the same ID. v6.0.0 deletes a seemingly random tab in the list when you click the garbage can icon on any of them (it's actually the first tab it finds in the Array with that ID). After commit dbee3fd, deleting works as expected as like it always should have.

v6.1.0 will be out soon with commit dbee3fd to address this issue correctly and hopefully completely.

**Comment by ssorallen** [comment]
[v6.1.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v6.1.0) is now released for Chrome and for Firefox. The duplicate IDs problem is highly likely the cause of this bug, and I am now no longer able to reproduce it.

If any of you upgrade and still run into this bug, please comment here and I will check this out again.
