### ISSUE TITLE
Table showing value ranges and limits + other guidance

### ISSUE THREAD

**Issue by Rod818** [tabwrangler/tabwrangler#218]
I'm very interested, but having been 'burned' before by apps that seemed like they would do the job but didn't, I suggest it would be helpful to new or prospective users to post a simple table showing the min/max range or other constraints, if any, for values of **all** in-app parameters, such as total tabs, total locked tabs, and time to wait before closing a tab.

Also, for exporting tabs, what are some examples of where to export 'to', and are the data (links) in native format so the site can be accessed directly from the 'backup' location (e.g., if exporting to MS Word (assuming that is possible), the site can readily be directly accessed via Ctrl+Click on the link)?  Does the export function inherently ensure that the data will always be retrievable in the format expected by Tab Wrangler?

Finally, what happens if Tab Wrangler is uninstalled?  What are the recommended steps a user would take before doing so in order to preserve **all** existing tab data?

**Comment by ssorallen** [comment]
Thank you for opening this issue, I appreciate the feedback. I will document the possible values in the README and more thoroughly explain the import/export format. Data is exported as JSON, so it’s plain text that another program could easily parse and use.

**Comment by ssorallen** [comment]
Import and export are now fully explained in the README. The file format is described in commit https://github.com/tabwrangler/tabwrangler/commit/e8674f6fb5dea457758d8ee6f17ea9504b2dbb75.
