### ISSUE TITLE
Can't remove individual tabs after restoring another

### ISSUE THREAD

**Issue by edjroot** [tabwrangler/tabwrangler#225]
Not sure about Chrome, but this is happening on Firefox: Open the corral, then restore one or more tabs, then click on the "trash" button of any other item - nothing happens.

Removing tabs will still work by selecting them and then clicking on the trash button that appears at the top.

**Comment by ssorallen** [comment]
Thank you for testing Firefox and for opening the issues!

**Comment by edjroot** [comment]
No problem! Hopefully I'll be able to do more than just open issues if I can get some free time.

**Comment by ingorichter** [comment]
Hm, this looks like an update issue for me. I tried this on Firefox and clicking the trash icon didn't remove the entry from the corral. After closing and reopening the corral, the entry was gone.

**Comment by edjroot** [comment]
I can't say for sure since I haven't been using the extension for some time, but if I remember correctly closing and reopening the corral didn't change anything for me, so maybe there's something weirder going on? (Or maybe it's just my memory failing me.)
