### ISSUE TITLE
Option: Limit total number of open tabs

### ISSUE THREAD

**Issue by edjroot** [tabwrangler/tabwrangler#226]
It's currently possible to completely "bypass" the tab limit by having as many open windows as you want with at most `n` tabs each (`n` being the limit you set). It would be nice to have the option to have at most `n` open tabs _in total_ rather than `n` per window.

**Comment by ssorallen** [comment]
I believe this is a duplicate of #95. I will close as a duplicate, but feel free to re-open if I am misunderstanding.

**Comment by edjroot** [comment]
Oh, I'm sorry. I took a quick look at all open issues before posting this, but I didn't notice from that title that it was about the same thing.

**Comment by ssorallen** [comment]
@edjroot No worries. I’d rather you open too many issues than too few. I’m fine doing the de-duplicating.
