### ISSUE TITLE
Feature Request: Option to Open Tabs from Tabwrangler Automatically

### ISSUE THREAD

**Issue by sahil48** [tabwrangler/tabwrangler#228]
I would like an option in tabwrangler to open tabs that have already been placed in the tab corral when a user-specified number of tabs are opened. This will help me get through tabs in the tab corral more easily, and not have to constantly reopen them after they get archived in the tab corral.

**Comment by ssorallen** [comment]
Thanks for the suggestion. If I understand correctly, I think your suggestion is the same as #122. Is that right?

I am going to close this as a duplicate, but let me know if you think there are any differences.
