### ISSUE TITLE
"Configure these shortcuts" link does nothing

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#229]
Firefox does not currently ship with a standard UI for customizing keyboard shortcuts like Chrome does. This needs to be handled manually by Tab Wrangler maybe?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by ssorallen** [comment]
Firefox has yet to add a keyboard customization page, so this is not yet resolved. I suggest checking out Firefox extensions that enable customizing keyboard shortcuts.

**Comment by ssorallen** [comment]
@sergeevabc It's certainly possible to build a custom solution for Tab Wrangler like those other two extensions have done, but I was hoping Firefox would implement its own central keyboard customization page like Chrome has. I didn't want to spend time on a feature that the browser should be providing.

Older versions of Firefox, before its big rewrite and redesign, provided a page for customizing keyboard shortcuts. That's why I was hoping the current Firefox would be re-implementing that feature.

**Comment by sergeevabc** [comment]
@ssorallen, indeed, this transition to Webextensions has deprived us of many freedoms to customize UI, and I ~~curse~~ mourn it every day. But the information ~~apocalypse~~ overload is always upon us, tabs are coming like a flood, so ~~Noah’s arc~~ Tab Wrangler is desperately required to define hotkeys today.

**Comment by sergeevabc** [comment]
Another FF 63-compatible extension which allows us to set hotkeys is [Cycle Input Focus Plus][1].

[1]: https://addons.mozilla.org/en-US/firefox/addon/cycle-input-focus-plus/?src=search

**Comment by Nyubis** [comment]
If customising the shortcuts isn't in the cards for Firefox, is disabling the shortcuts an option instead? I use Ctrl+Shift+E to open the network tab of my developer tools *very* frequently, and I'm tired of accidentally closing my tabs since I have this extension.

**Comment by ssorallen** [comment]
@Nyubis Thanks for bringing that up. I didn't realize the default shortcut was interfering with one that you use regularly.

I would like to provide a way to solve this but have not made the time to work on it yet.

**Comment by ssorallen** [comment]
Commit https://github.com/tabwrangler/tabwrangler/commit/75735e7035b3d231b68164dcfcb63da4a32b0bd8 removes the "Keyboard Shortcuts" sections in the "Options" tab.
* Firefox now has a dedicated extension keyboard config tool (go to _Tools > Add-ons and Themes > ⚙️ > Manage Extension Shortcuts_)
* Because both Firefox and Chrome have keyboard config tools, there's no need for Tab Wrangler to reimplement it. I view this the same way iOS has a central Notifications, Settings, etc. tool for all apps; a specific app does not need to add views for those common pieces

**Comment by ssorallen** [comment]
Commit https://github.com/tabwrangler/tabwrangler/commit/75735e7035b3d231b68164dcfcb63da4a32b0bd8 will be included in the next release, likely v6.10.0.
