### ISSUE TITLE
"Tab Lock" view should have an option to sort by ETA

### ISSUE THREAD

**Issue by Lucretiel** [tabwrangler/tabwrangler#230]
It'd be nice if the Tab Lock view could sort your tabs by ETA, so you can see which ones are soon to be closed.

I reviewed the code and it seems like this'd be pretty straightforward to add, so honestly I'm mostly filing this Issue as a reminder to myself to go in and implement it.

**Comment by ssorallen** [comment]
Yeah I like that idea, and I’m always happy to merge contributions. Thanks for taking a look.
