### ISSUE TITLE
Bug: Website shows up repeatedly in tab corral

### ISSUE THREAD

**Issue by sahil48** [tabwrangler/tabwrangler#234]
I am not sure how to reproduce this bug, but am posting this in the event anyone encounters this error and can explain how to produce it. I was using the latest version of Chrome (66.0.3359.181 64 bit) with Windows 10 64 bit.

The tab corral said that there were 500 tabs in the corral. When I opened it, I found out that most of them refered to the same website. Once I opened one of these entries with the same website, the number on the tab corral dropped to 15.

**Comment by quintrino** [comment]
Sounds similar to #172, what version of Tab Wrangler do you have?

**Comment by sahil48** [comment]
I just checked today. It is v5.12.0.

Just as in #172, the problem did occur after waking up my computer from sleep.

**Comment by KTamas** [comment]
@sahil48 @quintrino has this happened since?

**Comment by ssorallen** [comment]
This is a bug report on an outdated version of Tab Wrangler. Closing as "can not reproduce." Please re-open with new info if needed.
