### ISSUE TITLE
Shows # of tabs closed without option selected

### ISSUE THREAD

**Issue by emmaleigh** [tabwrangler/tabwrangler#245]
Hi, 

Recently the tab wrangler has started showing the number of tabs wrangled, even though I do not have that option selected. I can go into the options and turn it on and off again, and the number goes away temporarily, but still ends up coming back.

Thanks,
Emily

**Comment by ssorallen** [comment]
Thank you for the report. #232 was opened for this issue too. It’s really starting to annoy me, so I’ll try to get to it soon! I’ll close this issue since it’s a duplicate, but if you have other issues please feel free to open more.
