### ISSUE TITLE
Logo proposal for TABWRANGLER

### ISSUE THREAD

**Issue by ggabogarcia** [tabwrangler/tabwrangler#246]
Hello sir, I'm a graphic designer and I'm interested in open source projects. I would like to design a new logo for your project, it's completely free :)

**Comment by ssorallen** [comment]
Thank you, I would appreciate any design help you are willing to offer. I opened #168 to track some branding redesign, and if there’s anything else in there you’d be interested in helping complete that’d be great too. The Chrome Webstore accepts a few sizes of promotional images, and there is also the icon used in the browser URL bar. 

Thanks for your interest, and I’m excited to see anything you’d like to create.

**Comment by ssorallen** [comment]
I'm going to close this since we are discussing the logo in #168. Thanks again for all of your contributions, @ggabogarcia.
