### ISSUE TITLE
Tab Coral Empty

### ISSUE THREAD

**Issue by smb12345** [tabwrangler/tabwrangler#247]
I recently started using Tab Wrangler.  I had about 30 closed tabs in my tab coral yesterday.  I just booted up my computer and now my tab coral is empty.  I am using Chrome, and I am the only one using this computer.  

How do I retrieve the contents of my tab coral?

**Comment by ssorallen** [comment]
Thank you for the issue, and I apologize for the empty data. I am actively trying to fix this problem and understand its severity. Issue #241 is tracking this issue, so please see there for any updates.

The data may not be recoverable, but I am adding measures to prevent this from ever happening again.
