### ISSUE TITLE
[Feature] Fresh Tab Wrangler design

### ISSUE THREAD

**Issue by Voknehzyr** [tabwrangler/tabwrangler#250]
Hello 😸 
I'm working at new Tab Wrangler design that should look more modern, what do you think about this one?

**This is not final version and it still in WIP**

**Current tasks**:
- [x] Update code base to be able to work with BS4. 
- [x] Recode some parts of the extension for proper work with BS4.
- [x] Provide new navbar menu.
- [ ] 🚫 Integrate Material Design icons instead of using Glyphicons.
- [x] Use Font Awesome icons instead of using outdated Glyphicons.
- [ ] 🏃 Update checkboxes and text fields.
- [x] Restyle headings and fonts.
- [x] Add styles for **::selection** and scrollbar.
- [x] 🏃 Restyle bootstrap elements: Popup, Dropdown.
- [ ] Finalize code, remove unused properties and etc.
- [x] Publish changes in **new-design** branch.

🏃 - In work.
🚫 - Canceled due to technical reasons.

![2018-09-08_17-22-02](https://user-images.githubusercontent.com/10144091/45255240-5ce36580-b38c-11e8-9543-9936547f5981.png)
![2018-09-08_17-22-14](https://user-images.githubusercontent.com/10144091/45255242-5ead2900-b38c-11e8-8838-7d83355d8185.png)

**Comment by ssorallen** [comment]
Hey thanks, this is looking great! I was just looking at upgrading to Bootstrap 4, maybe we should do that and then customize to a new design. I can start a branch for BS4.

**Comment by Voknehzyr** [comment]
@ssorallen If you're going to update to Bootstrap 4, you will need to rewrite almost all your design because they fully moved to flexboxes, I was trying to set up new Bootstrap, but I was not sure about rewriting all extension UI renders...

**Comment by ssorallen** [comment]
https://github.com/tabwrangler/tabwrangler/tree/bootstrap-4

I tried using FontAwesome via a few NPM packages, but it added 200kb to Tab Wrangler. It might need Webpack 4 in order to drop unused modules, so I am going to try upgrading to Webpack 4. It's something I've wanted to experiment with anyway.

If you wanted to try Material icons instead, it might be easier to use with BS4.

**Comment by Voknehzyr** [comment]
Okay, can I ask how I can clone your currect branch to my fork? 😞

**Comment by Voknehzyr** [comment]
New BS version breaks Options tab.

**Comment by ssorallen** [comment]
@Voknehzyr Yeah I hadn't quite finished that branch. I'll push some more updates today.

**Comment by ssorallen** [comment]
@Voknehzyr A lot more of TW is now working in the bootstrap-4 branch. The OptionsTab looks better but still isn't perfect.

What do you think, do you want to build on this branch or off master?

**Comment by Voknehzyr** [comment]
Actually, I think Bootstrap 4 is more useful and adaptive, but it has a lot of changes in code.
I already rebuilt my project for bootstrap-4 branch, so I'll continue to work at new UI and features here, also I'm going to recode all views to make them look normally.

**Comment by Voknehzyr** [comment]
Slowly working at settings tab, what do you think? :)
![2018-09-15_23-57-18](https://user-images.githubusercontent.com/10144091/45590546-20db7200-b943-11e8-806a-c5d5920cc3ca.png)

**Comment by ssorallen** [comment]
@Voknehzyr That's looking great! I would drop the border around the settings area though since Tab Wrangler is already bound by a small popup. Other than that, it's looking really good.

**Comment by Voknehzyr** [comment]
I have big troubles with iconfonts, Font Awesome and other popular iconfonts looks too blurry on my screen, Idk why 😭

**Comment by ssorallen** [comment]
@Voknehzyr Can you send a pull request to the bootstrap-4 branch? I'll merge your changes, and then I can take a look at the icon fonts.

I did some work to customize for Tab Wrangler. Since TW only runs in Chrome and Firefox, I edited the CSS to use WOFF2 and only added that font file to the repo.

**Comment by Voknehzyr** [comment]
> I did some work to customize for Tab Wrangler. Since TW only runs in Chrome and Firefox, I edited the CSS to use WOFF2 and only added that font file to the repo.

I used fonts that using WOFF2 file format, looks like the problem in browser, not in fonts.
Also, there's a lot of *garbage* in my current code, I will try to clear it and then will send PR.
