### ISSUE TITLE
Hide Tabs Instead of Close Tabs on Firefox

### ISSUE THREAD

**Issue by Riajyuu** [tabwrangler/tabwrangler#252]
On Firefox, an API browser.tabs.tabhide() allow you to hide tabs instead of close them so you don't lose tab status.

**Comment by ssorallen** [comment]
That experimental functionality from Firefox is interesting, but I'm not sure it fits Tab Wrangler's model. According to the Firefox [tabs.hide() documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide):

> Hidden tabs are not automatically discarded: the code running in them continues to run. You can explicitly discard tabs whenever you hide them: although this is not appropriate in all situations, it will help to reduce the resources used by the browser.

Hiding is purely a cosmetic effect on the browser, the tabs still exist and still continue to run. That would change the model of TW, which enables cleaning up all resources of a tab once TW "closes" it.

**Comment by ssorallen** [comment]
@Riajyuu An extension that simply limits the number of tabs in the tab bar to a certain number and hides all others in a vertical list would be a nice simple way of handling too-many-tabs. For the time being, this functionality doesn't fit Tab Wrangler's model of actually closing tabs.

Tabs2List might accomplish what you're looking for: https://addons.mozilla.org/en-US/firefox/addon/tabs-2-list/?src=search

Thank you for the suggestion, and if there's another way I could make Tab Wrangler work for you please let me know.
