### ISSUE TITLE
Is there an option to remove website from lists?

### ISSUE THREAD

**Issue by nathan012** [tabwrangler/tabwrangler#257]
Hi there,
I couldn't find an option to remove a site from my lists. Can someone help? Thanks!

**To Reproduce**

**Expected behavior**

**Version (please complete the following information):**
 - OS: [e.g. Windows, MacOS]
 - Browser [e.g. Chrome, Firefox]
 - Version [e.g. v6.0.0]

**Comment by ssorallen** [comment]
@nathan012 You can hover over a row and click the trash icon to delete an item from your list. Or you can select the checkbox and then click the trash button at the top.

<img width="687" alt="screen shot 2018-10-15 at 8 58 01 am" src="https://user-images.githubusercontent.com/29612/46952298-6f6e5000-d058-11e8-8b85-609eb51cca87.png">

Is that what you were looking for?

**Comment by nathan012** [comment]
Thank you, I reinstalled and it worked.
