### ISSUE TITLE
Tabs disapeared

### ISSUE THREAD

**Issue by davask** [tabwrangler/tabwrangler#258]
**Describe the bug**
I have 21 tabs noted in the chrome extension icons but none when I click on the extension icon under Tab Corral

![hjtnufd](https://user-images.githubusercontent.com/482210/47413200-f2d12500-d76d-11e8-824d-b1fd3e390ad4.png)

**Version (please complete the following information):**
 - OS: Windows 8.1
 - Browser Chrome
 - Version v6.4.0

**Comment by ssorallen** [comment]
Thank you for opening the issue. I believe the root cause of this is in a 3rd-party library. I am tracking the data loss in #241 and will post any updates in that issue.

Please check #241 for any updates.
