### ISSUE TITLE
Tabs have disappeared

### ISSUE THREAD

**Issue by mistermaestr0** [tabwrangler/tabwrangler#263]
Hello,
I reformatted my Mac and made the mistake of not backing up my tabs in tab wrangler. Is there anyway to retrieve with account id or sync'd email on Chrome?

Thanks.

ID is: egnjhciaieeiiohknchakcodbpgjnchh

**Comment by ssorallen** [comment]
Unfortunately there is no way to recover the tabs from your old Mac. Your Tab Wrangler settings will be recovered when you log back into Chrome, but the closed tabs are stored only on your machine. Chrome's sync has limited capacity and is intended for only small amounts of data, like settings. 

It would be great to add an external syncing feature via Dropbox, iCloud, or something similar, but unfortunately I have not explored implementing that yet.

If you plan to change computers again, you can export your tabs from the Options tab and sync that file with an external service.
