### ISSUE TITLE
What happens if time over after I close Firefox, hibernate Windows?

### ISSUE THREAD

**Issue by ReporterX** [tabwrangler/tabwrangler#266]
Let's say I set the tab to auto-close after 1 hour. 
1. I close Firefox and re-open it after 1 hour. What would happen? All tabs closed immediately, or the countdown resume, or countdown starts over again?
2. What if Windows sleeps/hibernates?

Thank you.

**Comment by ReporterX** [comment]
I believe I found the answer. The countdown will start over if Firefox restarts in case 1.

I'm not sure if the countdown will keep and continue after sleep/hibernation.

**Comment by ssorallen** [comment]
Nothing to do here, this was a question.
