### ISSUE TITLE
Countdown survives even after browser restart

### ISSUE THREAD

**Issue by ReporterX** [tabwrangler/tabwrangler#268]
I set it to auto close half a day. However I will restart Firefox once in a while like several hours. Those tabs will never reach the countdown since they will all reset once restart. So sad. :'(

Save the countdown value of each tab, so countdown can survive after Firefox restarts, and can resume properly.

Countdown should survive even after sleep / hibernation too. Thank you.

**Comment by ssorallen** [comment]
I agree this should be implemented. Thank you for opening the issue.

This is captured in #130, so I will close this one as a duplicate.
