### ISSUE TITLE
THANK YOU FOR THIS IT IS BEAUTIFUL

### ISSUE THREAD

**Issue by jasikpark** [tabwrangler/tabwrangler#269]
I especially appreciate the specific options that you have included, with sane defaults:

I think I want it to close tabs when I have more than zero tabs open, but five is absolutely a good default setting for most users.

I was going to set it to like 2 or 3 hours but 20 minutes makes **much** more sense.

It's beautiful!!

![IMG_2041](https://user-images.githubusercontent.com/10626596/56992087-e4215b80-6b5e-11e9-9780-11c9ea3ec5ee.jpg)

**Comment by ssorallen** [comment]
I'm glad it's working for you! I'm happy to look at contributions if you'd like to change anything.

Thank you for the comments.
