### ISSUE TITLE
Blank option tab in Android Firefox

### ISSUE THREAD

**Issue by Ironlenny** [tabwrangler/tabwrangler#270]
**Describe the bug**
When I try to change options under Firefox Android, the options tab will be blank

**To Reproduce**
1. Click the menu icon
2. Click "Tab Wrangler"
3. A blank tab appears

**Expected behavior**
I expect a tab with options similar to the desktop version.

**Version (please complete the following information):**
 - OS: Android 5.1.1
 - Browser: Firefox
 - Version: 6.5.1

**Comment by ssorallen** [comment]
Thanks for reporting. I have not tested this extension on Android. Does it function at all? If not, I can delist it from Android since it's better to not list at all rather than be broken.

**Comment by ssorallen** [comment]
Going to close this one because I do not plan to test or release this on Android. I'm happy to accept pull requests related to Android, but I don't have an Android device and don't plan to maintain this extension for that platform.
