### ISSUE TITLE
Rethink the icon badge count

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#274]
Currently the badge over Tab Wrangler's browser icon shows the number of tabs in the corral. After a large number of tabs have been wrangled, that number is not useful.

What *is* useful is knowing when a tab has been wrangled, and right now there is no feedback for when that happens. Tab Wrangler could use the icon badge count to mean:

    the number of tabs wrangled in the last N minutes,
      where N is your "Close inactive tabs after" setting

**Comment by ssorallen** [comment]
This could help address #273.

**Comment by KTamas** [comment]
I would love to have an option to turn off seeing that number. I just don't want to see how many tabs were wrangled.

**Comment by ssorallen** [comment]
@KTamas, thanks for commenting. You can already disable the badge count! Go to Options > uncheck "Show # of closed tabs on the toolbar button".

Like you, I've never found that number to be useful to me. I could potentially disable the number by default in a future version.

**Comment by KTamas** [comment]
@ssorallen thanks! I realized shortly after commenting :)

**Comment by ssorallen** [comment]
Nothing to do here at the moment, this issue is more a note. The badge count is hidden by default.
