### ISSUE TITLE
NEW tab question

### ISSUE THREAD

**Issue by JohnSal** [tabwrangler/tabwrangler#286]
Hi, I was wondering if there is an open tab such as this https://imgur.com/h84TPhs that when i open the folder "rumors" as i the url i provided so that the "NEW TAB" will close when i open the contents in the "rumors" folder instead of staying open?

thx

**Comment by ssorallen** [comment]
New tabs have the URL `chrome://newtab`, so they are locked by default in Tab Wrangler. If you go to Options > Auto-Lock you can see the `chrome://` entry that doesn't the auto-locking. You can delete that entry if want want empty new tabs to be auto-closed by Tab Wrangler as well

<img width="736" alt="Screen Shot 2020-02-01 at 15 11 39" src="https://user-images.githubusercontent.com/29612/73598346-40a61280-4505-11ea-8d87-8736332d4c99.png">

Let me know if this doesn't solve your issue, and thanks for the question.
