### ISSUE TITLE
Tab Wrangler Material Redesign

### ISSUE THREAD

**Issue by rogi27** [tabwrangler/tabwrangler#287]
> This is the reworked idea of the #250 

I decided that moving Tab Wrangler to Material-UI components structure would be better for everything due to less amount of coding that gives me ability to create UI/UX faster, also it matches the Chromium's design much more.

To-do:
- [ ] Migrate all elements on new framework
- [ ] Redesign the pages for a better UX

Currently, using @mui-org/material-ui

**Comment by Voknehzyr** [comment]
First screenshots, @ssorallen free feel to criticize me to fix or explain something.

**Comment by ssorallen** [comment]
Thanks for all the work. I still need to make Dark Mode togglable in the Options tab, but for right now you can toggle it in your OS in order to see the dark mode CSS.

**Comment by Voknehzyr** [comment]
> Thanks for all the work. I still need to make Dark Mode togglable in the Options tab, but for right now you can toggle it in your OS in order to see the dark mode CSS.

Yeah, I will add dark mode too, just trying to make everything look better on light theme.
