### ISSUE TITLE
Please support automatic locking for tabs in a Tab Group

### ISSUE THREAD

**Issue by ffeldhaus** [tabwrangler/tabwrangler#289]
Google Chrome has a relatively [new feature called Tab Groups](https://bugs.chromium.org/p/chromium/issues/detail?id=905491#c25) which may soon be enabled by default. It would be very useful if Tab Wrangler would have an option to automatically lock tabs in a tab group (e.g. similar as pinned tabs).

**Comment by ssorallen** [comment]
Thanks for pointing out that new feature. I don't see any updates in the [Chrome Extension Tabs docs](https://developer.chrome.com/extensions/tabs) related to the feature. If tab groups make their way into Chrome permanently and are added to the extension API, Tab Wrangler could explore features related to them.

**Comment by proedie** [comment]
Tab Groups used to be a feature in Firefox. They have been removed but were replaced by an add-on called [Simple Tab Groups](https://github.com/drive4ik/simple-tab-groups). This works great and I'd love to see this add-on work together with Tabwrangler.

**Comment by dbushong** [comment]
Looks like they added something to the api dev channel: `groupId` that should help detect this: https://developer.chrome.com/extensions/tabs#type-Tab

**Comment by AlabasterAxe** [comment]
BTW, I took a crack at implementing this: #320 
It's not ready to be merged yet but it seems like the extension api is in Canary with a target release version of Chrome.

**Comment by johnw42** [comment]
It looks like this feature is being made official in the next release; see https://chromium-review.googlesource.com/c/chromium/src/+/2626891. I work on Chrome, and while I can't absolutely guarantee the change won't be reverted before the release, I'll be very surprised if that happens, so I think it would be a good idea to merge AlabasterAxe's change right away.

**Comment by ssorallen** [comment]
Thanks for commenting, @johnw42! What do you do on Chrome?

I'm on Chrome version 88.0.4324.182 and already have the groups feature without enabling anything extra. I was able to test @AlabasterAxe's PR. I'll release a new version of Tab Wrangler with the new feature.

This will go into Tab Wrangler v6.9.0

**Comment by macduy** [comment]
Hi @ssorallen, just wondering when would 6.9.0 be available? With the new Chrome tab group feature out, ability to keep them locked would come in really handy. Understood if things are busy though, will patiently wait.

**Comment by ssorallen** [comment]
@macduy v6.9.0 is now live for Firefox, and I submitted it to the Chrome Webstore. It will roll out automatically once it is reviewed.

**Comment by macduy** [comment]
Thanks! I see the update now, thanks for such a quick turnover.

**Comment by ssorallen** [comment]
@macduy Great, let me know if you see any issues.

I've got some larger design changes in mind after the addition of this feature and will try to outline them in GitHub Issues so others can hop on then if they are able to contribute. I tend to add features I know I will use but rely on others to add features I might not think of.
