### ISSUE TITLE
Restore tabs in the background

### ISSUE THREAD

**Issue by DooeyC** [tabwrangler/tabwrangler#294]
When your firefox is set to open links in the background you can have a tab loaded and continue to view the current tab. You then can easity switch to the new tab via Firefox's great ctrl-tab key shortcuts once the new tab finished loading.
You probably would expect this behavior as well when you restore a tab out of the tab corrals. This is not the case. The tab of the corral becomes immediately the active tab and you have to wait until it is loaded.
Firefox settings:
browser.tabs.loadInBackground: true
browser.tabs.loadDivertedInBackground: true

**Comment by ssorallen** [comment]
This looks like it would straightforward to do by passing `active: false` when creating the new tab via [`chrome.tabs.create`](https://developer.chrome.com/extensions/tabs#method-create). I like this idea.

**Comment by KTamas** [comment]
yeah, i like this as well.

**Comment by ssorallen** [comment]
* [`chrome.sessions.restore`](https://developer.chrome.com/docs/extensions/reference/api/sessions#method-restore) does not enable opening tabs in the background
* for sessions that cannot be restored they are already opened in the background

Closing as "not planned" due to API restrictions.
