### ISSUE TITLE
Extension icon too generic and too hard to find.

### ISSUE THREAD

**Issue by koryeh** [tabwrangler/tabwrangler#296]
Not exactly an issue, just a piece of feedback :) I love this extension, but I have one issue with it. I have in my work browser many extensions, most of them mandated by the org. Anytime I have to find the menu for this extension it takes me a few tries, because the icon has nothing to do with what the extension does, or with its name. It's just some nondescript shape with an arrow. It would be much easier to find if the icon was maybe a cowboy hat, a lasso, or something else cowboy related (maybe a boot, I don't know).

**Comment by ssorallen** [comment]
Thanks for the issue, and I agree the icon could be improved. A designer helped out on https://github.com/tabwrangler/tabwrangler/issues/246 a while ago, but I decided it wasn't a good direction to try to make the icon look like a tab; it wasn't recognizable in the address bar either.

I'd like to revisit the icon and make it simple and high contrast, maybe something as easy as a square with the letters "TW".

**Comment by ssorallen** [comment]
Closing as part of #437. Tab Wrangler needs a brand refresh including a better icon.
