### ISSUE TITLE
Reopened tabs do not enter the corral when wrangled

### ISSUE THREAD

**Issue by grapereader** [tabwrangler/tabwrangler#299]
**Describe the bug**
When a re-opened tab is wrangled, it disappears permanently.

**To Reproduce**
1. Reopen a tab from the corral
2. Wait for tab to be wrangled

**Expected behavior**
Tab should re-enter the corral.

**Version**
 - OS: Windows
 - Browser: Firefox
 - Version v6.8.0

**Comment by KTamas** [comment]
@grapereader is this still an issue?

**Comment by grapereader** [comment]
I have not seen it lately.

**Comment by KTamas** [comment]
okay, i'll close this for now.
