### ISSUE TITLE
Single Window is a Tab

### ISSUE THREAD

**Issue by madorian** [tabwrangler/tabwrangler#301]
I generally don't use tabs, I use one window per tab, so that I can use the operating system REGEX application switcher. 

Can Tab Wrangler also close windows that only has one tab?

Doesn't seem to work for me;)

**Comment by ssorallen** [comment]
Currently Tab Wrangler works only on tabs. Treating windows as tabs is being tracked in https://github.com/tabwrangler/tabwrangler/issues/95. The issue has been open for a very long time, but I only tend to work on this project in my free time. Submissions are welcome!

Thank you for opening the issue.
