### ISSUE TITLE
Solving the problem of disappearing tabs

### ISSUE THREAD

**Issue by QTaKs** [tabwrangler/tabwrangler#307]
I found one of the possible ways to recover lost tabs.
In the local files folder, we are only interested in the .ldb files and the .log file. I had 3 files: 003634.ldb, 003636.ldb and 003638.log. I transferred the .log file to another folder, renamed 003636.ldb to 003636.log. After launching the browser, all tabs are back.
Sorry for the English, wrote via google translate

Browser Opera
OS Archlinux
Ver 6.8.0

**Comment by ssorallen** [comment]
No further info needed for this issue. Thank you for reporting where to find lost tab data.
