### ISSUE TITLE
Tab Wrangler is trying to close manually closed tabs

### ISSUE THREAD

**Issue by devslow** [tabwrangler/tabwrangler#310]
**Describe the bug**
Tab that was manually closed is still being tracked to be closed. Because the tab was already closed it goes into a infinite loop of being wrangled and fills up the coral with non-existent tabs.

**To Reproduce**
1. Close tab manually
2. Wait the set wrangled time
3. Look at tab coral
4. See manually closed tab filling up tab coral

**Expected behavior**
When a tab is manually closed it should no longer be tracked and closed after wrangle time.

**Version (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version  81.0.1

**Comment by devslow** [comment]
This seems to be a conflict with https://github.com/ideaweb/firefox-safari-style. Not sure why some tabs do not show up or can be closed properly. I noticed the tabs that caused me to open this issue were still open using Tree Tabs. I switched back to the default theme and I'm no longer experiencing issue. 

Not sure if this should still be investigated or closed.

**Comment by ssorallen** [comment]
@devslow Thanks for the investigation, it sounds like Tree Tabs might be the issue. Could you link the exact extension?

It will be difficult to interact with other extensions properly.
