### ISSUE TITLE
Tabs wrangled when paused

### ISSUE THREAD

**Issue by Vantageright** [tabwrangler/tabwrangler#313]
**Describe the bug**
Tabs are automatically wrangled after the specified time, even when the wrangling is paused. 

**To Reproduce**
1. Pause tab wrangling
2. Wait 

**Expected behavior**
I expect it to not close tabs.
**Version (please complete the following information):**
 - OS: W7
 - Browser: Firefox
 - Version: 82.0.2 and 83

**Comment by ssorallen** [comment]
Thank you for the report, and I see the issue. I will have a fix out today. Sorry for the breakage, this is a bug introduced with #297 when trying to fix Issue #292.
