### ISSUE TITLE
Tab Wrangler completely revamped?

### ISSUE THREAD

**Issue by IamMeWasTaken** [tabwrangler/tabwrangler#327]
So I have been using Tab Wrangler since 2018 or so. But lately the button to open the extention, the pop out window where you can manage your tabs. Today I started digging and it seems like the extention completely changed from the tree overview to something automatic?

Does that mean that all my tabs I had in the tree overview are gone now?

**Comment by IamMeWasTaken** [comment]
God I am stupid I confused it with another extention. Dont pull two all nighters. Its not good.

**Comment by ssorallen** [comment]
Phew okay, I thought there might be a copycat extension with subpar experience. Glad you figured it out.
