### ISSUE TITLE
I would like my Tabwrangler as a full browser tab (Chrome).  I need that big view

### ISSUE THREAD

**Issue by dwlotter** [tabwrangler/tabwrangler#330]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by harl** [comment]
I'm not sure how this is accomplished in Chrome.
However, in Firefox (88.0), when I intend to open Tab Wrangler's options from the list of installed add-ons (extensions), it practically just opens Tab Wrangler in a new tab, showing exactly the same informations as it does when I click on the toolbar button.

There's no keyboard shortcut for this, and apparently no option to open Tab Wrangler in a tab as a default.

**Comment by marijuanatech** [comment]
In Chrome, simply right click the Tab Wrangler icon in the toolbar and choose "Options".  It'll open up in a full tab.

I believe you can also paste this URL into your address bar:
chrome-extension://egnjhciaieeiiohknchakcodbpgjnchh/popup.html
