### ISSUE TITLE
No icon in extension bar

### ISSUE THREAD

**Issue by SpareSimian** [tabwrangler/tabwrangler#331]
I have 14 extension icons to the right of my URL field and none are for Tab Wrangler. Where's the icon to launch the extension?

My tabs are disappearing so I know the extension is doing its cleaning action. I can get into the TW page if I go through More Tools | Extensions  and click the Details button for TW and then Extension options. 

**Versions
 - OS: Windows 10 2004
 - Chrome Version 89.0.4389.114 (Official Build) (64-bit)
 - Tab Wrangler 6.9.0

**Comment by SpareSimian** [comment]
Found it. Click the white "puzzle piece" icon at the far right of the extensions bar, just before the 3-dot menu icon. That opens a new Chrome Extensions menu. Find Tab Wrangler in there and click the push-pin icon next to it to enable its display in the main extensions bar. I also removed those that didn't make sense to clean up the display a bit.

**Comment by ssorallen** [comment]
Great, glad you were able to show up in the extension bar. Chrome has changed the UX there a bit.
