### ISSUE TITLE
Option to pause if corral gets full

### ISSUE THREAD

**Issue by ajsalminen** [tabwrangler/tabwrangler#338]
**Is your feature request related to a problem? Please describe.**
Sometimes I inadvertently run into the limit that I've set for Tab Wrangler and then I have to go check an older version of the browser data so I don't lose any tabs in the corral because I want to manually handle this case.

**Describe the solution you'd like**
I would like there to be an option that would pause tab wrangler instead of closing the oldest tabs in the corral when the limit is reached.

**Describe alternatives you've considered**
An alternative solution would be not to have the limit or have some way to restore tabs that have been pruned from the tab corral this way, something like a log that would record all operations for some window of time.

**Comment by KTamas** [comment]
yeah i think this would be pretty important to have.

**Comment by ssorallen** [comment]
If you reach 1,000 saved tabs in Tab Wrangler it's beyond the intention of this extension to keep a memory. 1,000 tabs is more than a person could reasonably think about so this feature is not what TW intends to add.

Happy to look at pull requests for this should someone still want the feature.
