### ISSUE TITLE
Optional injection into page context menu

### ISSUE THREAD

**Issue by altblue** [tabwrangler/tabwrangler#342]
**Is your feature request related to a problem? Please describe.**
Even vanilla page context menu is *already* cluttered: every *unused* entry is annoying.
Adding insult to injury, Wrangler even listens on `chrome:` pages, and while *paused*.

**Describe the solution you'd like**
Tab Wrangler › Options › Settings › 🗹 Enable Page Context Menu

**Describe alternatives you've considered**
Keep extension disabled (instead pause/resume).
Repack without `contextMenus` permission.

**Comment by marijuanatech** [comment]
I have this working. I need to do a little more testing and I'll try opening a pull request.

**Comment by KTamas** [comment]
@marijuanatech a PR for this would be more than welcome.

**Comment by emvaized** [comment]
Any updates on this? Context entry indeed clutters the menu a lot, would love to disable it

**Comment by aggrhm** [comment]
Any progress on this one? Would also appreciate it, seems like a simple fix.

**Comment by ssorallen** [comment]
Thanks for the reminder on this one. This will go into the next version (likely v7.6.0).

**Comment by aggrhm** [comment]
Amazing, thanks so much!
