### ISSUE TITLE
Question: Reset a tab's timer behavior

### ISSUE THREAD

**Issue by chiumax** [tabwrangler/tabwrangler#349]
Just curious, what is the behavior of "Reset a tab's timer only after it is active for 1 second"

being checked as opposed to being off.

![image](https://user-images.githubusercontent.com/28949652/134577960-4877f19a-7633-4dd9-b6d7-790a3d03a3f5.png)

**Comment by ssorallen** [comment]
Thanks for the question.

Typically a tab's timer is reset as soon as the tab becomes active. That means, for example, that Ctrl+Tab'ing through all active tabs quickly will reset all of the timers even if you didn't stop to look at the content of those tabs.

By checking the box, a tab's timer will only reset if it remains active for 1 full second. That likely means you looked at the content of the tab and therefore want to keep the tab "fresh."

Does that answer your question?

**Comment by ssorallen** [comment]
Please reopen if that didn't answer your question.
