### ISSUE TITLE
Transition to Manifest v3

### ISSUE THREAD

**Issue by ssorallen** [tabwrangler/tabwrangler#350]
Google Chrome is transitioning to [Manifest V3](https://developer.chrome.com/blog/mv2-transition/), and Tab Wrangler needs to follow along. Tab Wrangler will be allowed to update on V2 through January 2023, but this transition would ideally happen well in advance of that to ensure operation continues uninterrupted.

**Comment by funblaster22** [comment]
Ok, I took a look at this issue and [made my own fork with some changes](https://github.com/funblaster22/tabwrangler/tree/maniferst3), & it's really unfortunate that it seems MV3 doesn't have exactly suitable replacements for everything. Still need:
- [ ] [A way to share data between service worker & popup](https://developer.chrome.com/docs/extensions/reference/runtime/#method-getBackgroundPage)

**Comment by ssorallen** [comment]
Thanks for getting this started, @funblaster22. Google has a page about migrating from background pages to service workers: https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/

The following are things that need to happen:
1. [`tabTimes`](https://github.com/tabwrangler/tabwrangler/blob/master/app/js/tabmanager.ts#L22) needs to move into local storage. this will both fix some open issues (like https://github.com/tabwrangler/tabwrangler/issues/339) and ensure that when the service worker periodically starts up it will track tab times correctly
2. [set an alarm](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#alarms) to wake up on the shortest period possible, which is 1 minute according to v3 docs, and keep the service worker running for roughly 1 minute. Service workers are forcibly shut down after 5 minutes (according to https://bugs.chromium.org/p/chromium/issues/detail?id=1152255) so Tab Wrangler's life cycle will look like the following:

0 -> service worker A (SWA) starts
5s -> SWA polls for tabs to close
10s -> SWA polls for tabs to close
...
60s -> SWA stops polling, removes alarm and event listeners (it will get cleaned up by the browser)
60s -> service worker B (SWB) starts
5s -> SWB polls for tabs to close
...
etc. etc. etc.

**Comment by ssorallen** [comment]
I believe the above setup will work correctly the Chrome Manifest v3 world because no given service worker will live longer than 1 minute, and Tab Wrangler can still poll roughly every 5 seconds like it does now.

**Comment by ssorallen** [comment]
A contact on the Chrome Extensions dev relations team reached out and suggested using a heartbeat to keep the extensions existing background page alive after switching to Manifest v3.

Code example from the contact:

https://gist.github.com/patrickkettner/ab2e0f3a6341d41d9dbe81d42dfb04c4

They also linked to a relevant discussion in the chromimum-extensions Google Group: https://groups.google.com/a/chromium.org/g/chromium-extensions/c/hWEe4I93P_E/m/BfLasiaPAQAJ?utm_medium=email&utm_source=footer

**Comment by ofek** [comment]
What functionality will be lost after the upgrade?

**Comment by ssorallen** [comment]
@ofek As far as I know right now, no functionality will be lost. Thanks to the tip from the Chrome Extensions team, checking for stale tabs can work as it does right now. The most significant changes from v2 -> v3 are in functionality that Tab Wrangler.

Tab Wrangler v7.0.0 will work on Manifest v3, and any user-facing changes will be documented in the release notes.
