### ISSUE TITLE
Disable auto-save settings

### ISSUE THREAD

**Issue by wankio** [tabwrangler/tabwrangler#360]
So i'm just changed these two, and all my tabs is gone,  corral is overwritten

- Auto-close tabs only if i have more than : 150
- Remember up to: 100

Eg if i have 150+ opened tabs, when i'm typing in
- Auto-close tabs only if i have more than : 2 5 0 (by auto-saved settings, it will almost closed all tabs by each time i'm entered a number)
same as 'remember up to'

**Comment by funblaster22** [comment]
For me, the corral only got overwritten once a new tab is wrangled.

**Comment by ssorallen** [comment]
Consolidating this into https://github.com/tabwrangler/tabwrangler/issues/360

When the setting is changed there will now be a confirmation toast. If the number is decreasing there is a warning that reducing will truncate the list.

<img width=500 src=https://github.com/user-attachments/assets/3410e727-5186-4b5b-8c2f-f231c1bfdbb6>
