### ISSUE TITLE
[feature request] Add Shortcut to lock current tab

### ISSUE THREAD

**Issue by blauertee** [tabwrangler/tabwrangler#362]
It's a some clicks to lock the current tab, the most annoying thing is finding it in the "Tab Lock"- List of tabs, when you "did some tabs" in the last twenty minutes. A shortcut to do this would make my life easier.

Thanks for all the work on this wonderful AddOn!

**Comment by dlepold** [comment]
Yes, this feature is a must have. Sometimes I have a google research tab that will be the basis for some hours of work, and I want to keep it. Finding it in the list is quite difficult given that everything is so amazing and intuitive.  

Just a simple button: "Lock Current Tab" would save my day. 
![image](https://user-images.githubusercontent.com/6764649/153802411-5ac6c083-4d0d-40e2-a822-8f5c685bfebe.png)

And yes! Thanx for this amazing extension!

**Comment by ssorallen** [comment]
Thank you for the suggestion, this is an easy one that I agree is worth adding.

**Comment by blauertee** [comment]
Just to clarify in my original request I meant a keyboard shortcut not a button that is easier to reach but ofc both would be nice :)

**Comment by ssorallen** [comment]
This will be included in the next release (likely v6.10.0).
