### ISSUE TITLE
Merge a translation sources into one for: "tabs wrangled for $count$ or $percent$%"

### ISSUE THREAD

**Issue by xnuk** [tabwrangler/tabwrangler#364]
https://github.com/tabwrangler/tabwrangler/blob/a3f6c13de438ad3df85793e57b764989a039c915/app/js/CorralTab.js#L426-L432

Currently `corral_tabsWrangled`, `{totalTabsWrangled}`, `corral_tabsWrangled_or`, `{percentClosed}%` are all separated. This situation makes unable to change position of the words in translation. For example:
- In Korean (or possibly [Subject-Object-Verb structure] languages), putting a object before a verb is more natural: 300개 또는 10%의 탭이 닫힘 (300 counts or 10% of tabs are closed)
- In some languages like Finnish, there should be a space between numbers and percent sign (%). https://en.wikipedia.org/wiki/Percent_sign#Form_and_spacing

So I think the translation sources should be merged?

[Subject-Object-Verb structure]: https://en.wikipedia.org/wiki/Subject%E2%80%93object%E2%80%93verb

**Comment by ssorallen** [comment]
Great idea, I will take a look at this.
