### ISSUE TITLE
tab wrangler doesn't work. 

### ISSUE THREAD

**Issue by petebrag** [tabwrangler/tabwrangler#377]
**Describe the bug**
tabs don't close after any amount of time. 
**To Reproduce**
1. Go to '...'tab wranger
2. Click on '....'do anything
3. Scroll down to '....' do anything
4. See error - no closing

**Expected behavior**
they should close after x time. they don't 
**Version (please complete the following information):**
 - OS: [e.g. Windows, MacOS] macos 11.6.4 20g417 
 - Browser [e.g. Chrome, Firefox] chrome: Version 100.0.4896.127 (Official Build) (x86_64)

 - Version [e.g. v6.0.0] 6.9.0

**Comment by ssorallen** [comment]
Could you provide more info? How many tabs did you have open?

If you have fewer than the Max Tabs open, then no tabs will be closed.

**Comment by alinv04** [comment]
Same here.
I have three different instances of Chrome on Windows 11 with the latest TabWrangler, it hasn't close a single tab, no matter how many are open.

**Comment by ssorallen** [comment]
Closing this until there is more information for me to reproduce the issue.
