### ISSUE TITLE
"Close inactive tabs after" not working on Brave

### ISSUE THREAD

**Issue by joaosobreira** [tabwrangler/tabwrangler#383]
**Describe the bug**
On Brave, the "Close inactive tabs after" feature is not working

**To Reproduce**
_Steps to reproduce the behavior:_
Have a few tabs open
Go to Tab Wrangler extension on Brave
Go to "Options"
Set a low value in "Close inactive tabs after"
Wait for that amount of minutes to pass
Nothing happens

**Expected behavior**
Tab Wrangler should close the tabs and place them in the Tab Corral

**Version (please complete the following information):**
OS: [e.g. Windows, MacOS] Windows 10 Pro 21H2, build 19044.1889
Browser [e.g. Chrome, Firefox] Brave Browser Version 1.42.88 Chromium: 104.0.5112.81 (Official Build) (64-bit)
Version [e.g. v6.0.0] v6.9.0

**Comment by ssorallen** [comment]
Thank you for the report. I have never worked with Brave so I am going to need help understanding this issue.

**Comment by DasCanard** [comment]
I am also using Brave and got the same Issue.

**Comment by DasCanard** [comment]
Maybe this is helping out @ssorallen.

https://github.com/rNeomy/auto-tab-discard/issues/243

**Comment by DasCanard** [comment]
I tested in latest commit and it seems working now @joaosobreira 
Let me know if you need help compiling it.

Ur just use this build.
[chrome.zip](https://github.com/tabwrangler/tabwrangler/files/11088800/chrome.zip)

**Comment by ssorallen** [comment]
It sounds like this is now fixed from latest comment from @DasCanard?  Tab Wrangler uses [`.query({})`](https://developer.chrome.com/docs/extensions/reference/api/tabs#method-query) to get all tabs, which includes discarded tabs to the docs.
