### ISSUE TITLE
Can't set shortcuts on Firefox

### ISSUE THREAD

**Issue by roomedia** [tabwrangler/tabwrangler#384]
**Describe the bug**
'Configure these shortcuts' also tries to open 'chrome://extensions/configureCommands' even on Firefox

**To Reproduce**
1. Go to 'Options'
1. Scroll down to 'Keyboard Shortcuts'
1. Click on 'Configure these shortcuts'
1. Copy link and check the url

**Expected behavior**
Open configureCommands page

**Version (please complete the following information):**
 - OS: macOS Monterey v12.3.1
 - Browser: Firefox 103.0.2 (64-bit)
 - Version: v6.9.1

**Comment by ssorallen** [comment]
@roomedia In Firefox you can go to _Tools > Add-ons and Themes > ⚙ > Manage Extension Shortcuts_ to manage shortcuts for all extensions you have installed. I will add a description and remove the link in Firefox because it does not appear possible to deeplink to that options page.
