### ISSUE TITLE
Pause/resume invisible when Wrangler is in overflow menu on Firefox

### ISSUE THREAD

**Issue by grzegor** [tabwrangler/tabwrangler#385]
**Describe the bug**
When you have Tab Wrangler in the Overflow (the function that groups extensions icons in Firefox) the Pause/Resume button is hidden due to limited max width of drop down panels in this mode ([people are complaining to Mozilla](https://support.mozilla.org/en-US/questions/1350064) but is seems we're stuck with that limitation for now).

**To Reproduce**
1. Right click on empty space in Firefox toolbar and choose "Customize toolbar"
2. Move Tab Wrangler icon from the toolbar to the Overflow menu
3. Close "Customize" page
4. Click the Overflow Menu and choose Tab Wrangler
5. The Pause/Resume icon is not visible

**Expected behavior**
- minimum usability: put the Pause/Resume button above Tab Wrangler tabs if drop down panel width is too narrow 
- proper way: redesign panel UI to wrap elements if the panel width is lower than the default 

**Version:**
 - OS: macOS
 - Browser: Firefox
 - Version: Firefox 104.0.1, but the bug exists in every version issued in at least a year
 - Tab Wrangler version: 6.9.1

**Comment by ssorallen** [comment]
Thanks for the report, this is indeed crummy and I am able to reproduce it. Let me see if there are some style changes that would improve this.

**Comment by ssorallen** [comment]
This no longer appears to be an issue in Firefox v133 as of the time of this comment. The popup is full width and has no issue w/ the play/pause button.
