### ISSUE TITLE
Waterfox and Vivaldi loose all tabs after restart

### ISSUE THREAD

**Issue by Coool** [tabwrangler/tabwrangler#392]
Loose all tabs after restart. I think it's related to some crappy URL and amount of saved tabs ~ 1000. Can anybody reproduce the same behavior?

_MacOS - Waterfox [G5.0.1](https://github.com/WaterfoxCo/Waterfox/releases/tag/G5.0.1)  - Tab Wrangler v6.9.1_
_MacOS - Vivaldi 5.5.2805.38 - Tab Wrangler v6.9.0_

**Comment by Coool** [comment]
I will try to narrow down. But in Waterfox all worked great till 2022.10.12 (latest backup which Profile contained Tab Wrangler data) and when something happen (Waterfox major update or something else).

**Comment by ssorallen** [comment]
Closing as "can't repro" since this is an old issue on an unsupported browser. If you find further info or a way to reproduce please re-open.
