### ISSUE TITLE
Whitelist (invert URL list)

### ISSUE THREAD

**Issue by gishfishlx** [tabwrangler/tabwrangler#406]
**Is your feature request related to a problem? Please describe.**
Since there are way more tabs open from websites that i visit regularly it makes sense for me to rather close those than keep open everything else. Also the decluttered tabs would reveal whats has been hidden in between - so i can decide manually if these are still relevant.

**Describe the solution you'd like**
A button to invert the url protection list.

**Describe alternatives you've considered**
I've seen these feature has been requestet, got attention, somehow got lost on the way?

**Comment by ssorallen** [comment]
Thank you for this request, I am consolidating this into #378.
