### ISSUE TITLE
Is tex wrangler sending the browser history somewhere? 

### ISSUE THREAD

**Issue by JosephITA** [tabwrangler/tabwrangler#407]
Just a security question. I need to understand if I can use it or not.

**Comment by KTamas** [comment]
It does not.

**Comment by ssorallen** [comment]
I am the primary developer, and I can re-confirm what KTamas said: Tab Wrangler does not send your browsing history anywhere.

The Privacy Policy in the README outlines Tab Wrangler's data use policy as well: https://github.com/tabwrangler/tabwrangler#privacy-policy

**Comment by JosephITA** [comment]
Thank you guys.Good vibes to all of you!Tab wrangler is a great product that saves hours in this distracted world.BR,Giuseppe Sent from iPhoneOn 3 Feb 2023, at 00:45, Ross Allen ***@***.***> wrote:﻿
Closed #407 as completed.
