### ISSUE TITLE
Tab Wrangler leaving "New Tabs" when it closes tabs that have aged off.

### ISSUE THREAD

**Issue by dwarf-king-hreidmar** [tabwrangler/tabwrangler#408]
**Describe the bug**
Tab Wrangler seems to be leaving new tabs open instead of simply closing a tab when it reaches the max inactivity period.

**To Reproduce**
1. Run firefox 110.0 as a flatpak
2. Have tab wrangler close tabs after 20 minutes
3. Wait 20 minutes
4. Observe that the tab has now been replaced with a "New Tab" tab.

**Expected behavior**
The expired tab should just be closed

**Version (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 110.0
 - Version of Tab Wrangler: 6.10.1

**Comment by ssorallen** [comment]
This is currently working as inspected because the URL for new tabs in Firefox is `about:newtab` and Tab Wrangler's defaults tell it to ignore tabs that have `about:` in their URLs.

**Comment by dwarf-king-hreidmar** [comment]
That is good to know. Thank You
