### ISSUE TITLE
Tab Wrangler fails to close tabs with Chrome on MacOS

### ISSUE THREAD

**Issue by mrvalossa** [tabwrangler/tabwrangler#409]
**Describe the bug**
After timer has counted to zero, the tabs on Tab Lock view get "..." where the countdown number was, but the tab does not get closed and move to Corral. It just stays there on the Tab Lock view. 

**To Reproduce**
1. Go to any tab setting and change timer to a short period using the latest Chrome on MacOS Monterey.
2. Click on Tab Lock to view how tabs countdown finish. 
3. See how "..." shows in the Tab Lock view. Verify that the tabs indeed haven't closed and see that they are not in the Tab Corral either. 

**Expected behavior**
I expected tabs to close after timer gets to zero.

**Version (please complete the following information):**
 - OS: MacOS Monterey 12.6.3
 - Browser Chrome  
 - Version 110.0.5481.177 (Official Build) (arm64)

**Comment by mrvalossa** [comment]
Additional information: I am also using Quick Tabs, Marvellous Suspender (and Tabli, although redundant to Quick Tabs). The bug has been tested with The Marvellous Suspender disabled.

**Comment by ssorallen** [comment]
Do you have more than the minimum number of tabs open? The "..." will show until a new tab is opened and there are still fewer than the minimum number of tabs.

**Comment by ssorallen** [comment]
Closing until there is further information.
