### ISSUE TITLE
TabWrangler 7.0 seems to have a major JS memory leak

### ISSUE THREAD

**Issue by rhanton** [tabwrangler/tabwrangler#426]
**Describe the bug**
Suddenly when using v7.0, my Firefox memory usage on OSX 13.5.2 and Firefox 118.0.1 (64-bit) started going crazy. Instead of plugins using a few 100s of MB of memory when running `about:processes`, they were taking up 40-50+ GB of RAM till the O/S complained. I eventually tracked back the problem to tabwrangler. Will be using old version if possible for now.

Profiler says it is some type of JS promise callback.

**To Reproduce**
Run TabWrangler 7.0.

**Expected behavior**
Reasonable memory consumption.

**Version (please complete the following information):**
 - OS: OSX 13.5.2
 - Browser: Firefox 118.0.1
 - Version: 7.0

**Comment by ssorallen** [comment]
Wow okay thank you for flagging this, I will investigate immediately.

**Comment by rhanton** [comment]
Haha, this also caused me to write up a new "how to downgrade a plugin" in the mozilla support forums because the old answer was way out of date: https://support.mozilla.org/en-US/questions/1426539#answer-1608823

**Comment by ssorallen** [comment]
I was trusting another library, [tshaddix/webext-redux](https://github.com/tshaddix/webext-redux), to continue to use Redux and transition to Manifest v3 with minimal data syncing between popup + background page. v7 added that library. I suspect the memory leak is in their code, that is where I am looking right now.

**Comment by ssorallen** [comment]
I disabled v7.0.0 for right now, which re-enabled v6.10.1 in Firefox's releases. I have not yet found the cause of the leak.

**Comment by ssorallen** [comment]
The root of this was the addition of [webext-redux](https://github.com/tshaddix/webext-redux), and the most reliable solution is to remove Redux entirely. I added Redux to replace a bespoke cache implementation, but using Redux as a cache around [`chrome.storage`](https://developer.chrome.com/docs/extensions/reference/storage/) is needlessly complicated.

I am working on removing Redux entirely and adding [react-query](https://tanstack.com/query/latest) to query `chrome.storage` directly in React components as needed. This will remove the CPU- and memory-heavy IPC that was added in v7. Next release will be v7.1.0.

(Note: v7 was never released to Chrome)

**Comment by dholbert** [comment]
For what it's worth: we got a [bug report for high-memory-usage-in-Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1857768) which seems to in fact be this issue here.

**Comment by ssorallen** [comment]
@dholbert Whoa yes thank you, it is Tab Wrangler's fault. I don't have an ETA on removing Redux so I am going to publish v7.1.0 as a copy of v6.10.1, the previous version without the issue.

I thought removing v7 in Firefox Developer Hub would install the previous version for users, but that does not appear to be the case. Removing v7 prevented new installs, but there is a group of users with the broken version.

**Comment by dholbert** [comment]
Thanks! I'm not an expert in Firefox's add-ons manager, but I think your solution of releasing 6.x as an "update" 7.1.0 should indeed get those users rolled back (er, forward) to an unaffected version.
