### ISSUE TITLE
Alternative UI suggestion

### ISSUE THREAD

**Issue by xendk** [tabwrangler/tabwrangler#43]
If I may suggest an alternative UI:

Let the icon be an indicator of whether the current tab is locked or not, and let a simple click toggle the state for the current tab.

The corral and options would be available by right clicking the icon and selecting options (right-clickning the extensions I have available suggests that it's not possible to add more items to the popup menu).

**Comment by ssorallen** [comment]
Closing this. It hasn't been discussed in a long time.
