### ISSUE TITLE
Gmail restarts the timer every few seconds, gmail is not closing 

### ISSUE THREAD

**Issue by NM0000001** [tabwrangler/tabwrangler#434]
**Describe the bug**
Gmail is not closing

**To Reproduce**
1. Gmail in incognito in chrome
2. Tab Wrangler IS enabled for incognito
3. Watching the countdown in "tab lock" wrangler tab, gmail is resetting every few seconds despite no mouse or other movement
4. Prohibits gmail from closing

**Expected behavior**
Gmail should close same as other windows if no mouse or activity movement

**Version (please complete the following information):**
 - OS: MacOS  14.0 (23A344)
 - Browser Chrome
 - Version 118.0.5993.117

**Comment by ssorallen** [comment]
This is either because (a) Gmail is the active tab or (b) there are fewer than the minimum number of tabs open.

The UI needs to be improved to make it clear why the count is not decreasing, but this is working as intended.
