### ISSUE TITLE
Fast memory leak since 7.2.0

### ISSUE THREAD

**Issue by kit-ty-kate** [tabwrangler/tabwrangler#439]
**Describe the bug**
The extension fills up my 32GB of RAM in less than an hour since today’s upgrade which leads to Firefox crashing.
It was working fine with whatever version i had before.

**Version:**
 - OS: macOS/arm64 (M1Pro)
 - Browser: Firefox 119 and 120
 - Version: 7.2.0

**Comment by KTamas** [comment]
Memory leak for me as well. Not as bad as for kit-ty-kate but it's currently hogging 56% of the memory Firefox uses. To make things worse, it's using a LOT of CPU as well. See attached screenshots. the CPU usage meter in Firefox doesn't show which extension is hogging it but as soon as I turn off Tab Wrangler CPU usage goes to less than 1% so it's safe to say we found the culprit.

In its current form, the new version is unusable.

* OS: macOS/arm64 (M1 Pro)
* Browser: Firefox 120
* Version: 7.2.0

![CPU](https://github.com/tabwrangler/tabwrangler/assets/48946/b8b0b81c-de8e-4c76-9878-38bb88e8a853)
![Memory](https://github.com/tabwrangler/tabwrangler/assets/48946/15f21b03-edf7-4c6b-8a86-af70e7f3f433)

**Comment by bartekmotyl** [comment]
Sane here, eats memory very fast. 1GB consumed just after restarting FF.

**Comment by bartekmotyl** [comment]
And on MacOS: 
<img width="797" alt="image" src="https://github.com/tabwrangler/tabwrangler/assets/29923773/ad443b9e-8161-49a8-ad57-1339599c3dc3">

**Comment by lucmaga** [comment]
I'm having this issue also on Linux firefox 120.0

**Comment by ssorallen** [comment]
Releasing [v7.2.1](https://github.com/tabwrangler/tabwrangler/releases/tag/v7.2.1) right now to address these issues. Thank you for bearing with me; migrating to a model that will work for Chrome's Manifest v3 going forward required significant changes to how Tab Wrangler accesses browser storage. These changes were not optimal, and I am continuing to fix them.

I am testing these changes myself with 1,000 tabs in my storage and am trying new versions as soon as they go live in Firefox's Add-ons.

**Comment by ssorallen** [comment]
v7.2.1 is live for Firefox, please update when you get a chance. I am testing locally as well: https://addons.mozilla.org/en-US/firefox/addon/tabwrangler/

**Comment by bartekmotyl** [comment]
Trying the new version in FF on Windows now, so far looks good (the previous version immediately eaten lots of memory, now it looks stable).

**Comment by KTamas** [comment]
Loaded up the new version in my Chrome profiles, I only use Firefox at work so we'll see on Monday...

**Comment by ssorallen** [comment]
@KTamas I have not yet released the new version to Chrome. Firefox only has about 1,500 Tab Wrangler installs while Chrome as 50k+. Firefox is unwillingly my testing grounds! I am a full-time Firefox user though, I am living with these version updates too.

I have a few more changes to drop memory usage even further and stabilize.

**Comment by KTamas** [comment]
Ah that explains things. Nevertheless, can't hurt to try in Chrome anyways.

**Comment by kit-ty-kate** [comment]
I’ll continue to test it, but it looks like it’s fixed it for me. Thank you so much for this quick release!

**Comment by KTamas** [comment]
Seems promising in Chrome as well so far.

**Comment by ssorallen** [comment]
[v7.2.2](https://github.com/tabwrangler/tabwrangler/releases/tag/v7.2.2) further reduces memory usage by the background script. There will be necessary spikes in memory usage when the background script closes a tab (there always has been), but majority time will be negligible CPU and memory usage now.

Thank you for reporting this issue and please continue to if you see any other problems.

v7 was a necessary rewrite of Tab Wrangler's background script to continue operating in Chrome, and it's now possible to get back to features and other upgrades.
