### ISSUE TITLE
Microsoft Edge forgets locked tab status on (re)boot

### ISSUE THREAD

**Issue by azairvine** [tabwrangler/tabwrangler#456]
**Describe the bug**
Instances of Microsoft Edge will forget which tabs are locked upon (re)boot meaning that you have to manually lock all the relevant tabs each time you boot up your PC.  Applies across multiple profiles.  Shutting down Edge and reopening a profile does **not** forget which tabs are locked.

**To Reproduce**
Reboot PC > Open Edge profile > Check Tab Wrangler - Tab Lock status

**Expected behavior**
I'd expect Tab Wrangler to remember the status of locked tabs so they didn't have to be manually locked every time the PC is rebooted

**Version (please complete the following information):**

- OS: Win 10
- Browser: Microsoft Edge
- Version: 123.0.2420.97

**Comment by ssorallen** [comment]
This was fixed in commit https://github.com/tabwrangler/tabwrangler/commit/0ded8283f9a8f490d33e188d765422c5f50374d5 and is in v7.3.3 that will is pending review in Chrome Webstore currently.
