### ISSUE TITLE
It will auto unlock the locked tab

### ISSUE THREAD

**Issue by gwangjing** [tabwrangler/tabwrangler#462]
**Describe the bug**
It will auto unlock the locked tab

![image](https://github.com/tabwrangler/tabwrangler/assets/168408440/a0e7bd52-f6cd-41b7-810d-23a54a82892f)

**To Reproduce**

**Expected behavior**
I will need the locked tab remain locked, and always appear on the web page(without auto close)

**Version (please complete the following information):**

- OS: [e.g. Windows]
- Browser [e.g. Chrome]
- Version [e.g. v6.0.0]

**Comment by gwangjing** [comment]
Hi Team, please assist

**Comment by TheIndieArmy** [comment]
I have had the issue occur again a few times the last couple days, but the debug console showed the same errors I posted in the other thread. No new errors are shown after the issue occurs.

**Comment by ssorallen** [comment]
@TheIndieArmy Okay thank you. [v7.5.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v7.5.0) has a few changes that may address the issue, I am going to keep an eye on it. I submitted to the Chrome Web Store, it should be out in the next 24 hours.

**Comment by TheIndieArmy** [comment]
Unfortunately this is still occurring on 7.5.0.

**Comment by TheIndieArmy** [comment]
I believe this may be RAM related. I seem to only get the issue when my system is reaching 100% RAM usage.

**Comment by ssorallen** [comment]
@TheIndieArmy Okay thank you, high memory usage might lead to killing Tab Wrangler's Service Worker. I will take a look at start up of the Service Worker and how it could be losing the state of locked tabs.

**Comment by ssorallen** [comment]
@TheIndieArmy Thanks for the note about memory - it did lead me to investigate Chrome's auto-discarding. I uncovered a bug where auto-discarded tabs get new IDs, but those IDs are not updates in the list of locked tab IDs.

I am going to get a fix together for this.
