### ISSUE TITLE
Does not close any tabs in Vivaldi

### ISSUE THREAD

**Issue by leflamm** [tabwrangler/tabwrangler#464]
**Describe the bug**
Does not close any tabs in Vivaldi. Had worked fine up until recently.

**To Reproduce**
Open a bunch of tabs. Set "Close inactive tabs after" to 0 sec. Empty list for Autolock. Nothing happens.

**Expected behavior**
Tabs would be closed.

**Version (please complete the following information):**

- OS: Ubuntu 24.4 (already present with 23.10)
- Browser: Vivaldi
- Version: 6.7.3329.21 (Stable channel) stable (64-bit)

**Comment by leflamm** [comment]
Remove + Reinstall solved this. Thx!

**Comment by ssorallen** [comment]
Thank you for reporting. I am unfamiliar with Vivaldi, but please open issues if you do run into other issues.
