### ISSUE TITLE
Auto-close appears to have stopped working in Chrome

### ISSUE THREAD

**Issue by jasonrhodes** [tabwrangler/tabwrangler#466]
**Describe the bug**
I've used this extension for many years and as of a week or two ago (maybe more, not sure) it has stopped auto-closing tabs on multiple machines for me, in Chrome.

**To Reproduce**

1. Open Chrome
2. Verify extension is enabled
3. Verify options to auto-close more than n tabs after x minutes (see screenshot below)
4. Open more than n tabs, wait more than x minutes
5. Notice that no tabs have been auto-closed

**Expected behavior**
Tabs over the n tabs limit (that have not been otherwise locked) should be auto-closed after x minutes.

**Versions (please complete the following information):**

- OS: MacOS Sonoma 14.4.1
- Browser: Chrome (Version 123.0.6312.105 (Official Build) (arm64))
- Version: v7.4.0

<img width="467" alt="Screenshot 2024-05-09 at 10 33 43 AM" src="https://github.com/tabwrangler/tabwrangler/assets/159370/fb97d01a-8511-437f-a078-277f5e418ecc">
<img width="691" alt="Screenshot 2024-05-09 at 10 34 21 AM" src="https://github.com/tabwrangler/tabwrangler/assets/159370/ad27f0ab-688c-4719-be27-1f30e5d2c279">
<img width="1950" alt="Screenshot 2024-05-09 at 10 34 56 AM" src="https://github.com/tabwrangler/tabwrangler/assets/159370/c4c3959a-13a7-49b3-ab36-b6c0b1bbab0e">

**Comment by ssorallen** [comment]
@jasonrhodes Thank you for the report. This latest v7 version appears to have core issues, I appreciate you reporting. I am first going to add a lot of logging to find out what's going on because it is proving difficult to reproduce.

I was waiting as long as possible to release this version, but it was required by Chrome's upgrade to [Manifest v3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3).

I will post here in the next week or two as I am able to begin debugging.

**Comment by ssorallen** [comment]
Likely related to https://github.com/tabwrangler/tabwrangler/discussions/465.

**Comment by ssorallen** [comment]
@jasonrhodes Could you see if Tab Wrangler is throwing any exceptions?
1. Window > Extensions
2. Toggle "Developer Mode" in upper right corner
3. Click the "service worker" link that says `Inspect views service worker` next to Tab Wrangler
4. Paste any red exceptions from the Console into this issue

Thank you.

**Comment by jasonrhodes** [comment]
Sorry, I'm just seeing these responses! I'll run in dev mode and report back with exceptions if I have them.

**Comment by theJ3H** [comment]
I'm also having problems with tabs not getting closed. I have 7.5.0 from chrome store. I don't see errors in the service worker console.
I noticed that in the tab lock section of the extension where the tab timer is displayed, sometimes the timer just resets to the original time as if the tab was opened, even when the tab is in the background. Most of the time when I click on the extension Icon and switch to the Tab lock section all timers will show 60:00 or a few seconds less than that.
Hopefully you can figure this out, really love this extension

**Comment by theJ3H** [comment]
yup that fixed it, sorry my bad

**Comment by ssorallen** [comment]
@theJ3H No worries. I need to improve that because I agree it is misleading. Glad to hear Tab Wrangler is working for you!

**Comment by jasonrhodes** [comment]
This works for me, too! Thanks for the fix.

**Comment by ssorallen** [comment]
@jasonrhodes Glad to hear it and thanks again for posting the issue. Please feel free to post in the future.

**Comment by zicodes** [comment]
Not sure if I was affected (I'm on v7.5.1), but Text Wrangler works great once I've set it to `Auto-close inactive tabs if there are more than` to `0`. My default is for Text Wrangler to just close anything that is open and it works great!
