### ISSUE TITLE
Timer is reset after hiberante/sleep

### ISSUE THREAD

**Issue by kaste** [tabwrangler/tabwrangler#468]
**Describe the bug**
 
After wake up of the PC (Brave/Window 11) the timer reset.  I just reproduced this on my machine.  Press the button on the computer to "turn it off" (which is hibernate), press again to start the computer, see the timer page:

![image](https://github.com/tabwrangler/tabwrangler/assets/8558/ecef5db7-190d-413d-837a-d8a3984a68aa)

I pretty much think this worked before but since yesterday it is not.   Typically TW did a cleanup "over night" (after hibernate) as I would expect.  But maybe you thought that this is too surprising and annoying and changed that behavior?

I have this long 480 timer, basically like the Arc browsers default.

**Comment by ssorallen** [comment]
Thank you for the report. I discovered the root cause of this and fixed it in https://github.com/tabwrangler/tabwrangler/pull/470 alongside the fix for #462.

This fix will go into v7.6.0.

**Comment by pshute** [comment]
I'm on v7.5.1, and I'm still having this issue, but I'm having trouble reproducing it. I often find lots of tabs still open with timers on 180 minutes when I wake my laptop in the morning. The laptop is set to sleep after an hour. Manually making it sleep doesn't reproduce the behaviour.

I have "Auto-close inactive tabs if there are more than" set to 1, and the  timeout set to 180 minutes.

Changing the timeout to 30 minutes makes it work as expected.

Win 11, Chrome 125.0.6422.142 (Official Build) (64-bit).
