### ISSUE TITLE
Insta suspend ctrl clicked tabs

### ISSUE THREAD

**Issue by bennerosen** [tabwrangler/tabwrangler#475]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i open 10-50 tabs that i need to systematically go trough and chrome wants to load them all up at the same time. This takes a lot of resources.

**Describe the solution you'd like**
I would prefer tabs load for the first time when I actually visit the tab.

**Describe alternatives you've considered**
Well I haven't found any other extension which provides this feature so this is a chance to be the first! :D

**Comment by ssorallen** [comment]
Interesting, it does seem like this would be possible. By listening to `onCreated` and calling `discard()` on the new tab if it is not active you could likely achieve this functionality. The browser may begin loading the tab before that function call, it would take some testing to see.
