### ISSUE TITLE
Tabwrangler use incomplete value being typed to trim wrangled tabs (insufficient debounce?)

### ISSUE THREAD

**Issue by berdario** [tabwrangler/tabwrangler#480]
**Describe the bug**

When modifying the maxTabs setting, lots wrangled tabs can get deleted.

, and you type `9`, `0`, `0`... You're likely going to find that the wrangled tabs get truncated down to 9 or 90 (instead of 900), because . 
**To Reproduce**

1. Go to the options, with the goal of overwriting the default maxTabs (1000) with 900, highlight/select `1000`
2. type `9`, `0`, `0`
3. You're likely going to find that the wrangled tabs get truncated down to 9 or 90 (instead of 900) because Tabwrangler starts to use the value before you even finished typing

I see that there's debounce setup to avoid this kind of behaviour, but I suspect that the [value currently used (150)](https://github.com/tabwrangler/tabwrangler/blob/ec9f060e3968db7d8f372c84f2c0d1941eea6149/app/js/OptionsTab.tsx#L151) might not be enough to avoid this.

**Expected behavior**

Either the value is used only on removing focus from the field, or the debouncing is increased.

Doing the latter would be relatively straightforward, but since the same debouncing logic is used for lots of other fields, and that I'm not sure what would be a reasonable value, I decided to first file an issue about this.

**Comment by ssorallen** [comment]
Related to https://github.com/tabwrangler/tabwrangler/issues/360 - auto-saving is causing list truncation.

**Comment by ssorallen** [comment]
Consolidating this into https://github.com/tabwrangler/tabwrangler/issues/167

When the setting is changed there will now be a confirmation toast. If the number is decreasing there is a warning that reducing will truncate the list.

<img width=500 src=https://github.com/user-attachments/assets/3410e727-5186-4b5b-8c2f-f231c1bfdbb6>
