### ISSUE TITLE
Option to operate on a per-window basis

### ISSUE THREAD

**Issue by luhn** [tabwrangler/tabwrangler#77]
I'd like an option for TabWrangler to operate on a per-window basis.

For example, let's say I set my tab limit to 5 and inactive time to 20 minutes and enable this new per-window optional.  Then TabWrangler will close inactive tabs after 20 minutes only if there are more than 5 tabs open _in that window_.

**Comment by eorroe** [comment]
I'm confused I see this issue was closed, but I don't get how to use this?

**Comment by ssorallen** [comment]
It sounds like previously it counted all tabs across all windows, but this change made the option "tabs per window." How do you expect this to work?

**Comment by eorroe** [comment]
Per window, but when I pause on a different window it shows as paused for all windows. Or is the functionality working, but the icon is showing paused for each window?

**Comment by luhn** [comment]
This change only changes tab count to be per window.  Pausing is still a global action.

**Comment by eorroe** [comment]
Oh, my fault. Yes, that's always worked, would be awesome to have that as an option that can be switched. I'll make a separate issue for the pause per window

**Comment by ssorallen** [comment]
@eorroe Great, thanks. I'm going to lock this convo. A new issue is the place to chat.
