### ISSUE TITLE
Use chrome.storage API to save the tabs so that they get synced across devices

### ISSUE THREAD

**Issue by aziz** [tabwrangler/tabwrangler#83]
Using multiple machines, it's really painful to lose some tabs in other machine tabwrangler list. Use chrome.storage API to save the tabs so that they get synced across devices.

**Comment by jm3** [comment]
that would be interesting. chrome already kinda has tab syncing, sorta, but this would be much more hardcore than that.

**Comment by jacobSingh** [comment]
I think the poster means sync rather than storage alone... We use it for
configuration but not tabs. We could do that, but might not be preferred by
everyone. Make a setting?

Best
J

**Comment by phraymond** [comment]
Would really like this.

**Comment by KTamas** [comment]
i would love, love, love this, this is the no. 1 thing i miss from tab wrangler. that being said the quota limit is an issue so it'd take quite a bit of effort to implement. still, high priority.

**Comment by ssorallen** [comment]
Closing as "will not implement" because sync storage is a small area. A potential solution would be to integrate with a 3rd party storage area, like Dropbox, but that is not planned at this time.
