### ISSUE TITLE
Suspend tab option

### ISSUE THREAD

**Issue by heyvoon** [tabwrangler/tabwrangler#86]
There is another extension that I've been using in conjuntion with TabWrangler that is called "The Great suspender"  (http://goo.gl/OjWhr). Like that name says. It suspends inactive Tabs.
![image](https://cloud.githubusercontent.com/assets/3281265/4934356/f00bbed6-65a0-11e4-8f39-655421c83cca.png)

It would be awesome if we could have the suspend tab option built in TabWrangler already! So we could choose to suspend the tab instead of closing it. Also we could use suspend lists for this feature, so sites on this list gets suspended instead of closed or vise-versa. Or maybe choose the default actions to suspend a tab instead of closing. Or suspend and then after certain amount of time of inactivity close it. I don't know how to implement. I am not a programmer. I am just giving my suggestion. 

Thanks everyone in advance.

**Comment by ssorallen** [comment]
I like the "suspend and then after certain amount of time of inactivity close it" idea!

**Comment by KTamas** [comment]
i believe chrome pretty much does this nowadays, so closing this.
