### ISSUE TITLE
Make per-window behaviour optional

### ISSUE THREAD

**Issue by ghost** [tabwrangler/tabwrangler#95]
Agh! I wondered why Tab Wrangler was "broken", and now I see it was deliberate! (issue #77) Obviously took me a while to notice, but then if I was more organized I wouldn't need Tab Wrangler in the first place :-)

This change made Tab Wrangler useless to me, as I tend to have lots of windows with a few tabs, so TW almost never closes anything for me. This really should be a configuration option.

I guess for now I'll fork the repo and revert that change, but it would be great to have it as an option in the official release.

**Comment by weedy** [comment]
I want to second this.
I install TW on PCs where I think the user might not understand the point of tabs/windows. (Parents, aunts/uncles, some friends in English majors).

And I've gotten support requests a multiple times now where the PC is lagging but it ends up being chrome with 75 windows minimized with 1 or 2 tabs in them.

When I set the "close inactive after X" setting I was expecting it to kill off windows too if necessary...

**Comment by ssorallen** [comment]
> When I set the "close inactive after X" setting I was expecting it to kill off windows too if necessary...

I've tried to read through all outstanding issues and only now saw your comment. Windows with just 1 tab now close thanks to #161.

**Comment by RobStorm** [comment]
I also don't want this per window, because then I just open a bunch of windows. It seems like this used to be the default functionality. I was wondering why so many tabs were not closing.

**Comment by ssorallen** [comment]
This is implemented by #453 and will go into the next release. 9 years old, this might be the oldest issue I've ever closed.
